; Automatically generated by jvm2m5

(in-package "M5")
(include-book "models/jvm/m5/m5" :dir :system)

(defconst *FdlibmTranslitN$Log10*
    (make-class-decl
     "FdlibmTranslitN$Log10"
     '("java/lang/Object")
     '(nil
       (methodref "java/lang/Object" "<init>:()V" 0)            ; 1
       (methodref "FdlibmTranslitN" "access$000:(D)I" 2)        ; 2
       (methodref "FdlibmTranslitN" "access$100:(D)I" 2)        ; 3
       (integer 1048576)                                        ; 4
       (integer 2147483647)                                     ; 5
       (class (ref -1) "FdlibmTranslitN$Log10")                 ; 6
       (double #xc350000000000000) ; -0x1.0p54 -1.8014398509481984E16   ; 7
       nil
       (fieldref "FdlibmTranslitN$Log10" "zero:D" 2)            ; 9
       (double #x4350000000000000) ; 0x1.0p54 1.8014398509481984E16     ; 10
       nil
       (integer 2146435072)                                     ; 12
       (integer -2147483648)                                    ; 13
       (integer 1048575)                                        ; 14
       (methodref "FdlibmTranslitN" "access$300:(DI)D" 3)       ; 15
       (double #x3d59fef311f12b36) ; 0x1.9fef311f12b36p-42 3.694239077158931E-13        ; 16
       nil
       (double #x3fdbcb7b1526e50e) ; 0x1.bcb7b1526e50ep-2 0.4342944819032518    ; 18
       nil
       (methodref "FdlibmTranslitN$Log" "compute:(D)D" 2)       ; 20
       (double #x3fd34413509f6000) ; 0x1.34413509f6p-2 0.30102999566361177      ; 21
       nil
       (class (ref -1) "java/lang/Object")                      ; 23
       (utf8)                                                   ; 24
       (utf8)                                                   ; 25
       (utf8)                                                   ; 26
       (utf8)                                                   ; 27
       (utf8)                                                   ; 28
       (utf8)                                                   ; 29
       (utf8)                                                   ; 30
       (utf8)                                                   ; 31
       (utf8)                                                   ; 32
       (utf8)                                                   ; 33
       (utf8)                                                   ; 34
       (utf8)                                                   ; 35
       (utf8)                                                   ; 36
       (utf8)                                                   ; 37
       (utf8)                                                   ; 38
       (utf8)                                                   ; 39
       (utf8)                                                   ; 40
       (name-and-type "<init>:()V")                             ; 41
       (class (ref -1) "FdlibmTranslitN")                       ; 42
       (name-and-type "access$000:(D)I")                        ; 43
       (name-and-type "access$100:(D)I")                        ; 44
       (utf8)                                                   ; 45
       (utf8)                                                   ; 46
       (utf8)                                                   ; 47
       (name-and-type "zero:D")                                 ; 48
       (name-and-type "access$300:(DI)D")                       ; 49
       (class (ref -1) "FdlibmTranslitN$Log")                   ; 50
       (name-and-type "compute:(D)D")                           ; 51
       (utf8)                                                   ; 52
       (utf8)                                                   ; 53
       (utf8)                                                   ; 54
       (utf8)                                                   ; 55
       (utf8)                                                   ; 56
       (utf8)                                                   ; 57
       (utf8)                                                   ; 58
       (utf8)                                                   ; 59
       (utf8)                                                   ; 60
      )
     #x00000020                                                 ; SUPER
     '(
       ("two54:D" #x00000018)                                   ; STATIC FINAL
       ("ivln10:D" #x00000018)                                  ; STATIC FINAL
       ("log10_2hi:D" #x00000018)                               ; STATIC FINAL
       ("log10_2lo:D" #x00000018)                               ; STATIC FINAL
       ("zero:D" #x00000008)                                    ; STATIC
      )
     (list
      '("<init>:()V" #x00000002                                 ; PRIVATE
        ; line_number #1727
        (aload_0)                                               ; 0
        (invokespecial 1)                                       ; 1 java.lang.Object.<init>:()V
        (return)                                                ; 4
       )
      '("compute:(D)D" #x00000808                               ; STATIC STRICT
        ; line_number #1747
        (dload_0)                                               ; 0
        (invokestatic 2)                                        ; 1 FdlibmTranslitN.access$000:(D)I
        (istore 8)                                              ; 4
        ; line_number #1748
        (dload_0)                                               ; 6
        (invokestatic 3)                                        ; 7 FdlibmTranslitN.access$100:(D)I
        (istore 9)                                              ; 10
        ; line_number #1750
        (iconst_0)                                              ; 12
        (istore 7)                                              ; 13
        ; line_number #1751
        (iload 8)                                               ; 15
        (ldc 4)                                                 ; 17 1048576
        (if_icmpge 50)                                          ; 19
        ; line_number #1752
        (iload 8)                                               ; 22
        (ldc 5)                                                 ; 24 2147483647
        (iand)                                                  ; 26
        (iload 9)                                               ; 27
        (ior)                                                   ; 29
        (ifne 11)                                               ; 30
        ; line_number #1753
        (ldc2_w 7)                                              ; 33 -1.8014398509481984E16d
        (getstatic 9)                                           ; 36 FdlibmTranslitN$Log10.zero:D
        (ddiv)                                                  ; 39
        (dreturn)                                               ; 40
        ; line_number #1754
        (iload 8)                                               ; 41
        (ifge 11)                                               ; 43
        (dload_0)                                               ; 46
        (dload_0)                                               ; 47
        (dsub)                                                  ; 48
        (getstatic 9)                                           ; 49 FdlibmTranslitN$Log10.zero:D
        (ddiv)                                                  ; 52
        (dreturn)                                               ; 53
        ; line_number #1755
        (iinc 7 -54)                                            ; 54
        (dload_0)                                               ; 57
        (ldc2_w 10)                                             ; 58 1.8014398509481984E16d
        (dmul)                                                  ; 61
        (dstore_0)                                              ; 62
        ; line_number #1756
        (dload_0)                                               ; 63
        (invokestatic 2)                                        ; 64 FdlibmTranslitN.access$000:(D)I
        (istore 8)                                              ; 67
        ; line_number #1758
        (iload 8)                                               ; 69
        (ldc 12)                                                ; 71 2146435072
        (if_icmplt 7)                                           ; 73
        (dload_0)                                               ; 76
        (dload_0)                                               ; 77
        (dadd)                                                  ; 78
        (dreturn)                                               ; 79
        ; line_number #1759
        (iload 7)                                               ; 80
        (iload 8)                                               ; 82
        (bipush 20)                                             ; 84
        (ishr)                                                  ; 86
        (sipush 1023)                                           ; 87
        (isub)                                                  ; 90
        (iadd)                                                  ; 91
        (istore 7)                                              ; 92
        ; line_number #1760
        (iload 7)                                               ; 94
        (ldc 13)                                                ; 96 -2147483648
        (iand)                                                  ; 98
        (bipush 31)                                             ; 99
        (iushr)                                                 ; 101
        (istore 6)                                              ; 102
        ; line_number #1761
        (iload 8)                                               ; 104
        (ldc 14)                                                ; 106 1048575
        (iand)                                                  ; 108
        (sipush 1023)                                           ; 109
        (iload 6)                                               ; 112
        (isub)                                                  ; 114
        (bipush 20)                                             ; 115
        (ishl)                                                  ; 117
        (ior)                                                   ; 118
        (istore 8)                                              ; 119
        ; line_number #1762
        (iload 7)                                               ; 121
        (iload 6)                                               ; 123
        (iadd)                                                  ; 125
        (i2d)                                                   ; 126
        (dstore_2)                                              ; 127
        ; line_number #1763
        (dload_0)                                               ; 128
        (iload 8)                                               ; 129
        (invokestatic 15)                                       ; 131 FdlibmTranslitN.access$300:(DI)D
        (dstore_0)                                              ; 134
        ; line_number #1764
        (dload_2)                                               ; 135
        (ldc2_w 16)                                             ; 136 3.694239077158931E-13d
        (dmul)                                                  ; 139
        (ldc2_w 18)                                             ; 140 0.4342944819032518d
        (dload_0)                                               ; 143
        (invokestatic 20)                                       ; 144 FdlibmTranslitN$Log.compute:(D)D
        (dmul)                                                  ; 147
        (dadd)                                                  ; 148
        (dstore 4)                                              ; 149
        ; line_number #1765
        (dload 4)                                               ; 151
        (dload_2)                                               ; 153
        (ldc2_w 21)                                             ; 154 0.30102999566361177d
        (dmul)                                                  ; 157
        (dadd)                                                  ; 158
        (dreturn)                                               ; 159
       )
      '("<clinit>:()V" #x00000008                               ; STATIC
        ; line_number #1737
        (dconst_0)                                              ; 0
        (putstatic 9)                                           ; 1 FdlibmTranslitN$Log10.zero:D
        (return)                                                ; 4
       ))
     '(ref -1)))