; Automatically generated by jvm2m5

(in-package "M5")
(include-book "models/jvm/m5/m5" :dir :system)

(defconst *FdlibmTranslit$Cbrt*
    (make-class-decl
     "FdlibmTranslit$Cbrt"
     '("java/lang/Object")
     '()
     '(
      "B1:I"
      "B2:I"
      "C:D"
      "D:D"
      "E:D"
      "F:D"
      "G:D")
     '(nil
       (methodref "java/lang/Object" "<init>:()V" 0)           ; 1
       (methodref "FdlibmTranslit" "access$000:(D)I" 2)        ; 2
       (integer -2147483648)                                   ; 3
       (integer 2146435072)                                    ; 4
       (methodref "FdlibmTranslit" "access$100:(D)I" 2)        ; 5
       (methodref "FdlibmTranslit" "access$400:(DI)D" 3)       ; 6
       (integer 1048576)                                       ; 7
       (integer 1129316352)                                    ; 8
       (class (ref -1) "FdlibmTranslit$Cbrt")                  ; 9
       (integer 696219795)                                     ; 10
       (integer 715094163)                                     ; 11
       (double #x3fe15f15f15f15f1) ; 0x1.15f15f15f15f1p-1 0.5428571428571428   ; 12
       nil
       (double #x3fd6db6db6db6db7) ; 0x1.6db6db6db6db7p-2 0.35714285714285715  ; 14
       nil
       (double #x3ff9b6db6db6db6e) ; 0x1.9b6db6db6db6ep0 1.6071428571428572    ; 16
       nil
       (double #x3ff6a0ea0ea0ea0f) ; 0x1.6a0ea0ea0ea0fp0 1.4142857142857144    ; 18
       nil
       (double #xbfe691de2532c834) ; -0x1.691de2532c834p-1 -0.7053061224489796 ; 20
       nil
       (methodref "FdlibmTranslit" "access$200:(DI)D" 3)       ; 22
       (class (ref -1) "java/lang/Object")                     ; 23
       (utf8)                                                  ; 24
       (utf8)                                                  ; 25
       (utf8)                                                  ; 26
       (utf8)                                                  ; 27
       (utf8)                                                  ; 28
       (utf8)                                                  ; 29
       (utf8)                                                  ; 30
       (utf8)                                                  ; 31
       (utf8)                                                  ; 32
       (utf8)                                                  ; 33
       (utf8)                                                  ; 34
       (utf8)                                                  ; 35
       (utf8)                                                  ; 36
       (utf8)                                                  ; 37
       (utf8)                                                  ; 38
       (utf8)                                                  ; 39
       (utf8)                                                  ; 40
       (utf8)                                                  ; 41
       (name-and-type "<init>:()V")                            ; 42
       (class (ref -1) "FdlibmTranslit")                       ; 43
       (name-and-type "access$000:(D)I")                       ; 44
       (name-and-type "access$100:(D)I")                       ; 45
       (name-and-type "access$400:(DI)D")                      ; 46
       (utf8)                                                  ; 47
       (utf8)                                                  ; 48
       (utf8)                                                  ; 49
       (name-and-type "access$200:(DI)D")                      ; 50
       (utf8)                                                  ; 51
       (utf8)                                                  ; 52
       (utf8)                                                  ; 53
       (utf8)                                                  ; 54
       (utf8)                                                  ; 55
       (utf8)                                                  ; 56
       (utf8)                                                  ; 57
       (utf8)                                                  ; 58
      )
     (list
      '("<init>:()V" nil
        ; line_number #587
        (aload_0)                                               ; 0
        (invokespecial 1)                                       ; 1 java.lang.Object.<init>:()V
        (return)                                                ; 4
       )
      '("compute:(D)D" nil
        ; line_number #601
        (dconst_0)                                              ; 0
        (dstore 7)                                              ; 1
        ; line_number #604
        (dload_0)                                               ; 3
        (invokestatic 2)                                        ; 4 FdlibmTranslit.access$000:(D)I
        (istore_2)                                              ; 7
        ; line_number #605
        (iload_2)                                               ; 8
        (ldc 3)                                                 ; 9 -2147483648
        (iand)                                                  ; 11
        (istore 11)                                             ; 12
        ; line_number #606
        (iload_2)                                               ; 14
        (iload 11)                                              ; 15
        (ixor)                                                  ; 17
        (istore_2)                                              ; 18
        ; line_number #607
        (iload_2)                                               ; 19
        (ldc 4)                                                 ; 20 2146435072
        (if_icmplt 7)                                           ; 22
        ; line_number #608
        (dload_0)                                               ; 25
        (dload_0)                                               ; 26
        (dadd)                                                  ; 27
        (dreturn)                                               ; 28
        ; line_number #610
        (iload_2)                                               ; 29
        (dload_0)                                               ; 30
        (invokestatic 5)                                        ; 31 FdlibmTranslit.access$100:(D)I
        (ior)                                                   ; 34
        (ifne 5)                                                ; 35
        ; line_number #611
        (dload_0)                                               ; 38
        (dreturn)                                               ; 39
        ; line_number #613
        (dload_0)                                               ; 40
        (iload_2)                                               ; 41
        (invokestatic 6)                                        ; 42 FdlibmTranslit.access$400:(DI)D
        (dstore_0)                                              ; 45
        ; line_number #615
        (iload_2)                                               ; 46
        (ldc 7)                                                 ; 47 1048576
        (if_icmpge 38)                                          ; 49
        ; line_number #616
        (dload 7)                                               ; 52
        (ldc 8)                                                 ; 54 1129316352
        (invokestatic 6)                                        ; 56 FdlibmTranslit.access$400:(DI)D
        (dstore 7)                                              ; 59
        ; line_number #617
        (dload 7)                                               ; 61
        (dload_0)                                               ; 63
        (dmul)                                                  ; 64
        (dstore 7)                                              ; 65
        ; line_number #618
        (dload 7)                                               ; 67
        (dload 7)                                               ; 69
        (invokestatic 2)                                        ; 71 FdlibmTranslit.access$000:(D)I
        (iconst_3)                                              ; 74
        (idiv)                                                  ; 75
        (ldc 10)                                                ; 76 696219795
        (iadd)                                                  ; 78
        (invokestatic 6)                                        ; 79 FdlibmTranslit.access$400:(DI)D
        (dstore 7)                                              ; 82
        (goto 16)                                               ; 84
        ; line_number #620
        (dload 7)                                               ; 87
        (iload_2)                                               ; 89
        (iconst_3)                                              ; 90
        (idiv)                                                  ; 91
        (ldc 11)                                                ; 92 715094163
        (iadd)                                                  ; 94
        (invokestatic 6)                                        ; 95 FdlibmTranslit.access$400:(DI)D
        (dstore 7)                                              ; 98
        ; line_number #624
        (dload 7)                                               ; 100
        (dload 7)                                               ; 102
        (dmul)                                                  ; 104
        (dload_0)                                               ; 105
        (ddiv)                                                  ; 106
        (dstore_3)                                              ; 107
        ; line_number #625
        (ldc2_w 12)                                             ; 108 0.5428571428571428d
        (dload_3)                                               ; 111
        (dload 7)                                               ; 112
        (dmul)                                                  ; 114
        (dadd)                                                  ; 115
        (dstore 5)                                              ; 116
        ; line_number #626
        (dload 7)                                               ; 118
        (ldc2_w 14)                                             ; 120 0.35714285714285715d
        (ldc2_w 16)                                             ; 123 1.6071428571428572d
        (dload 5)                                               ; 126
        (ldc2_w 18)                                             ; 128 1.4142857142857144d
        (dadd)                                                  ; 131
        (ldc2_w 20)                                             ; 132 -0.7053061224489796d
        (dload 5)                                               ; 135
        (ddiv)                                                  ; 137
        (dadd)                                                  ; 138
        (ddiv)                                                  ; 139
        (dadd)                                                  ; 140
        (dmul)                                                  ; 141
        (dstore 7)                                              ; 142
        ; line_number #629
        (dload 7)                                               ; 144
        (iconst_0)                                              ; 146
        (invokestatic 22)                                       ; 147 FdlibmTranslit.access$200:(DI)D
        (dstore 7)                                              ; 150
        ; line_number #630
        (dload 7)                                               ; 152
        (dload 7)                                               ; 154
        (invokestatic 2)                                        ; 156 FdlibmTranslit.access$000:(D)I
        (iconst_1)                                              ; 159
        (iadd)                                                  ; 160
        (invokestatic 6)                                        ; 161 FdlibmTranslit.access$400:(DI)D
        (dstore 7)                                              ; 164
        ; line_number #633
        (dload 7)                                               ; 166
        (dload 7)                                               ; 168
        (dmul)                                                  ; 170
        (dstore 5)                                              ; 171
        ; line_number #634
        (dload_0)                                               ; 173
        (dload 5)                                               ; 174
        (ddiv)                                                  ; 176
        (dstore_3)                                              ; 177
        ; line_number #635
        (dload 7)                                               ; 178
        (dload 7)                                               ; 180
        (dadd)                                                  ; 182
        (dstore 9)                                              ; 183
        ; line_number #636
        (dload_3)                                               ; 185
        (dload 7)                                               ; 186
        (dsub)                                                  ; 188
        (dload 9)                                               ; 189
        (dload_3)                                               ; 191
        (dadd)                                                  ; 192
        (ddiv)                                                  ; 193
        (dstore_3)                                              ; 194
        ; line_number #637
        (dload 7)                                               ; 195
        (dload 7)                                               ; 197
        (dload_3)                                               ; 199
        (dmul)                                                  ; 200
        (dadd)                                                  ; 201
        (dstore 7)                                              ; 202
        ; line_number #640
        (dload 7)                                               ; 204
        (dload 7)                                               ; 206
        (invokestatic 2)                                        ; 208 FdlibmTranslit.access$000:(D)I
        (iload 11)                                              ; 211
        (ior)                                                   ; 213
        (invokestatic 6)                                        ; 214 FdlibmTranslit.access$400:(DI)D
        (dstore 7)                                              ; 217
        ; line_number #641
        (dload 7)                                               ; 219
        (dreturn)                                               ; 221
       ))
     '(ref -1)))