; Automatically generated by jvm2m5

(in-package "M5")
(include-book "models/jvm/m5/m5" :dir :system)

(defconst *FdlibmTranslit$Exp*
    (make-class-decl
     "FdlibmTranslit$Exp"
     '("java/lang/Object")
     '()
     '(
      "one:D"
      "halF:[D"
      "huge:D"
      "twom1000:D"
      "o_threshold:D"
      "u_threshold:D"
      "ln2HI:[D"
      "ln2LO:[D"
      "invln2:D"
      "P1:D"
      "P2:D"
      "P3:D"
      "P4:D"
      "P5:D")
     '(nil
       (methodref "java/lang/Object" "<init>:()V" 0)           ; 1
       (methodref "FdlibmTranslit" "access$300:()D" 0)         ; 2
       (methodref "FdlibmTranslit" "access$500:()I" 0)         ; 3
       (methodref "FdlibmTranslit" "access$000:(D)I" 2)        ; 4
       (integer 2147483647)                                    ; 5
       (integer 1082535490)                                    ; 6
       (integer 2146435072)                                    ; 7
       (integer 1048575)                                       ; 8
       (methodref "FdlibmTranslit" "access$100:(D)I" 2)        ; 9
       (class (ref -1) "FdlibmTranslit$Exp")                   ; 10
       (double #x40862e42fefa39ef) ; 0x1.62e42fefa39efp9 709.782712893384      ; 11
       nil
       (double #x7ff0000000000000) ; Infinity Infinity         ; 13
       nil
       (double #xc0874910d52d3051) ; -0x1.74910d52d3051p9 -745.1332191019411   ; 15
       nil
       (integer 1071001154)                                    ; 17
       (integer 1072734898)                                    ; 18
       (fieldref "FdlibmTranslit$Exp" "ln2HI:[D" 1)            ; 19
       (fieldref "FdlibmTranslit$Exp" "ln2LO:[D" 1)            ; 20
       (double #x3ff71547652b82fe) ; 0x1.71547652b82fep0 1.4426950408889634    ; 21
       nil
       (fieldref "FdlibmTranslit$Exp" "halF:[D" 1)             ; 23
       (integer 1043333120)                                    ; 24
       (double #x7e37e43c8800759c) ; 0x1.7e43c8800759cp996 1.0E300     ; 25
       nil
       (double #x3fc555555555553e) ; 0x1.555555555553ep-3 0.16666666666666602  ; 27
       nil
       (double #xbf66c16c16bebd93) ; -0x1.6c16c16bebd93p-9 -0.0027777777777015593      ; 29
       nil
       (double #x3f11566aaf25de2c) ; 0x1.1566aaf25de2cp-14 6.613756321437934E-5        ; 31
       nil
       (double #xbebbbd41c5d26bf1) ; -0x1.bbd41c5d26bf1p-20 -1.6533902205465252E-6     ; 33
       nil
       (double #x3e66376972bea4d0) ; 0x1.6376972bea4dp-25 4.1381367970572385E-8        ; 35
       nil
       (double #x4000000000000000) ; 0x1.0p1 2.0               ; 37
       nil
       (methodref "FdlibmTranslit" "access$400:(DI)D" 3)       ; 39
       (double #x0170000000000000) ; 0x1.0p-1000 9.332636185032189E-302        ; 40
       nil
       (double #x3fe0000000000000) ; 0x1.0p-1 0.5              ; 42
       nil
       (double #xbfe0000000000000) ; -0x1.0p-1 -0.5            ; 44
       nil
       (double #x3fe62e42fee00000) ; 0x1.62e42feep-1 0.6931471803691238        ; 46
       nil
       (double #xbfe62e42fee00000) ; -0x1.62e42feep-1 -0.6931471803691238      ; 48
       nil
       (double #x3dea39ef35793c76) ; 0x1.a39ef35793c76p-33 1.9082149292705877E-10      ; 50
       nil
       (double #xbdea39ef35793c76) ; -0x1.a39ef35793c76p-33 -1.9082149292705877E-10    ; 52
       nil
       (class (ref -1) "java/lang/Object")                     ; 54
       (utf8)                                                  ; 55
       (utf8)                                                  ; 56
       (utf8)                                                  ; 57
       (double #x3ff0000000000000) ; 0x1.0p0 1.0               ; 58
       nil
       (utf8)                                                  ; 60
       (utf8)                                                  ; 61
       (utf8)                                                  ; 62
       (utf8)                                                  ; 63
       (utf8)                                                  ; 64
       (utf8)                                                  ; 65
       (utf8)                                                  ; 66
       (utf8)                                                  ; 67
       (utf8)                                                  ; 68
       (utf8)                                                  ; 69
       (utf8)                                                  ; 70
       (utf8)                                                  ; 71
       (utf8)                                                  ; 72
       (utf8)                                                  ; 73
       (utf8)                                                  ; 74
       (utf8)                                                  ; 75
       (utf8)                                                  ; 76
       (utf8)                                                  ; 77
       (utf8)                                                  ; 78
       (utf8)                                                  ; 79
       (utf8)                                                  ; 80
       (utf8)                                                  ; 81
       (utf8)                                                  ; 82
       (utf8)                                                  ; 83
       (name-and-type "<init>:()V")                            ; 84
       (class (ref -1) "FdlibmTranslit")                       ; 85
       (name-and-type "access$300:()D")                        ; 86
       (name-and-type "access$500:()I")                        ; 87
       (name-and-type "access$000:(D)I")                       ; 88
       (name-and-type "access$100:(D)I")                       ; 89
       (utf8)                                                  ; 90
       (utf8)                                                  ; 91
       (utf8)                                                  ; 92
       (name-and-type "ln2HI:[D")                              ; 93
       (name-and-type "ln2LO:[D")                              ; 94
       (name-and-type "halF:[D")                               ; 95
       (name-and-type "access$400:(DI)D")                      ; 96
       (utf8)                                                  ; 97
       (utf8)                                                  ; 98
       (utf8)                                                  ; 99
       (utf8)                                                  ; 100
       (utf8)                                                  ; 101
       (utf8)                                                  ; 102
       (utf8)                                                  ; 103
       (utf8)                                                  ; 104
       (utf8)                                                  ; 105
       (utf8)                                                  ; 106
       (utf8)                                                  ; 107
      )
     (list
      '("<init>:()V" nil
        ; line_number #931
        (aload_0)                                               ; 0
        (invokespecial 1)                                       ; 1 java.lang.Object.<init>:()V
        (return)                                                ; 4
       )
      '("compute:(D)D" nil
        ; line_number #953
        (invokestatic 2)                                        ; 0 FdlibmTranslit.access$300:()D
        (dstore 4)                                              ; 3
        (invokestatic 2)                                        ; 5 FdlibmTranslit.access$300:()D
        (dstore 6)                                              ; 8
        ; line_number #954
        (invokestatic 3)                                        ; 10 FdlibmTranslit.access$500:()I
        (istore 12)                                             ; 13
        ; line_number #957
        (dload_0)                                               ; 15
        (invokestatic 4)                                        ; 16 FdlibmTranslit.access$000:(D)I
        (istore 14)                                             ; 19
        ; line_number #959
        (iload 14)                                              ; 21
        (bipush 31)                                             ; 23
        (ishr)                                                  ; 25
        (iconst_1)                                              ; 26
        (iand)                                                  ; 27
        (istore 13)                                             ; 28
        ; line_number #961
        (iload 14)                                              ; 30
        (ldc 5)                                                 ; 32 2147483647
        (iand)                                                  ; 34
        (istore 14)                                             ; 35
        ; line_number #965
        (iload 14)                                              ; 37
        (ldc 6)                                                 ; 39 1082535490
        (if_icmplt 60)                                          ; 41
        ; line_number #967
        (iload 14)                                              ; 44
        (ldc 7)                                                 ; 46 2146435072
        (if_icmplt 31)                                          ; 48
        ; line_number #968
        (iload 14)                                              ; 51
        (ldc 8)                                                 ; 53 1048575
        (iand)                                                  ; 55
        (dload_0)                                               ; 56
        (invokestatic 9)                                        ; 57 FdlibmTranslit.access$100:(D)I
        (ior)                                                   ; 60
        (ifeq 7)                                                ; 61
        ; line_number #969
        (dload_0)                                               ; 64
        (dload_0)                                               ; 65
        (dadd)                                                  ; 66
        (dreturn)                                               ; 67
        ; line_number #971
        (iload 13)                                              ; 68
        (ifne 7)                                                ; 70
        (dload_0)                                               ; 73
        (goto 4)                                                ; 74
        (dconst_0)                                              ; 77
        (dreturn)                                               ; 78
        ; line_number #974
        (dload_0)                                               ; 79
        (ldc2_w 11)                                             ; 80 709.782712893384d
        (dcmpl)                                                 ; 83
        (ifle 7)                                                ; 84
        ; line_number #975
        (ldc2_w 13)                                             ; 87 Infinityd
        (dreturn)                                               ; 90
        ; line_number #977
        (dload_0)                                               ; 91
        (ldc2_w 15)                                             ; 92 -745.1332191019411d
        (dcmpg)                                                 ; 95
        (ifge 5)                                                ; 96
        ; line_number #978
        (dconst_0)                                              ; 99
        (dreturn)                                               ; 100
        ; line_number #983
        (iload 14)                                              ; 101
        (ldc 17)                                                ; 103 1071001154
        (if_icmple 91)                                          ; 105
        ; line_number #985
        (iload 14)                                              ; 108
        (ldc 18)                                                ; 110 1072734898
        (if_icmpge 33)                                          ; 112
        ; line_number #987
        (dload_0)                                               ; 115
        (getstatic 19)                                          ; 116 FdlibmTranslit$Exp.ln2HI:[D
        (iload 13)                                              ; 119
        (daload)                                                ; 121
        (dsub)                                                  ; 122
        (dstore 4)                                              ; 123
        ; line_number #988
        (getstatic 20)                                          ; 125 FdlibmTranslit$Exp.ln2LO:[D
        (iload 13)                                              ; 128
        (daload)                                                ; 130
        (dstore 6)                                              ; 131
        ; line_number #989
        (iconst_1)                                              ; 133
        (iload 13)                                              ; 134
        (isub)                                                  ; 136
        (iload 13)                                              ; 137
        (isub)                                                  ; 139
        (istore 12)                                             ; 140
        (goto 45)                                               ; 142
        ; line_number #991
        (ldc2_w 21)                                             ; 145 1.4426950408889634d
        (dload_0)                                               ; 148
        (dmul)                                                  ; 149
        (getstatic 23)                                          ; 150 FdlibmTranslit$Exp.halF:[D
        (iload 13)                                              ; 153
        (daload)                                                ; 155
        (dadd)                                                  ; 156
        (d2i)                                                   ; 157
        (istore 12)                                             ; 158
        ; line_number #992
        (iload 12)                                              ; 160
        (i2d)                                                   ; 162
        (dstore 10)                                             ; 163
        ; line_number #993
        (dload_0)                                               ; 165
        (dload 10)                                              ; 166
        (getstatic 19)                                          ; 168 FdlibmTranslit$Exp.ln2HI:[D
        (iconst_0)                                              ; 171
        (daload)                                                ; 172
        (dmul)                                                  ; 173
        (dsub)                                                  ; 174
        (dstore 4)                                              ; 175
        ; line_number #995
        (dload 10)                                              ; 177
        (getstatic 20)                                          ; 179 FdlibmTranslit$Exp.ln2LO:[D
        (iconst_0)                                              ; 182
        (daload)                                                ; 183
        (dmul)                                                  ; 184
        (dstore 6)                                              ; 185
        ; line_number #997
        (dload 4)                                               ; 187
        (dload 6)                                               ; 189
        (dsub)                                                  ; 191
        (dstore_0)                                              ; 192
        (goto 27)                                               ; 193
        ; line_number #998
        (iload 14)                                              ; 196
        (ldc 24)                                                ; 198 1043333120
        (if_icmpge 17)                                          ; 200
        ; line_number #1000
        (ldc2_w 25)                                             ; 203 1.0E300d
        (dload_0)                                               ; 206
        (dadd)                                                  ; 207
        (dconst_1)                                              ; 208
        (dcmpl)                                                 ; 209
        (ifle 10)                                               ; 210
        ; line_number #1001
        (dconst_1)                                              ; 213
        (dload_0)                                               ; 214
        (dadd)                                                  ; 215
        (dreturn)                                               ; 216
        ; line_number #1004
        (iconst_0)                                              ; 217
        (istore 12)                                             ; 218
        ; line_number #1008
        (dload_0)                                               ; 220
        (dload_0)                                               ; 221
        (dmul)                                                  ; 222
        (dstore 10)                                             ; 223
        ; line_number #1009
        (dload_0)                                               ; 225
        (dload 10)                                              ; 226
        (ldc2_w 27)                                             ; 228 0.16666666666666602d
        (dload 10)                                              ; 231
        (ldc2_w 29)                                             ; 233 -0.0027777777777015593d
        (dload 10)                                              ; 236
        (ldc2_w 31)                                             ; 238 6.613756321437934E-5d
        (dload 10)                                              ; 241
        (ldc2_w 33)                                             ; 243 -1.6533902205465252E-6d
        (dload 10)                                              ; 246
        (ldc2_w 35)                                             ; 248 4.1381367970572385E-8d
        (dmul)                                                  ; 251
        (dadd)                                                  ; 252
        (dmul)                                                  ; 253
        (dadd)                                                  ; 254
        (dmul)                                                  ; 255
        (dadd)                                                  ; 256
        (dmul)                                                  ; 257
        (dadd)                                                  ; 258
        (dmul)                                                  ; 259
        (dsub)                                                  ; 260
        (dstore 8)                                              ; 261
        ; line_number #1010
        (iload 12)                                              ; 263
        (ifne 19)                                               ; 265
        ; line_number #1011
        (dconst_1)                                              ; 268
        (dload_0)                                               ; 269
        (dload 8)                                               ; 270
        (dmul)                                                  ; 272
        (dload 8)                                               ; 273
        (ldc2_w 37)                                             ; 275 2.0d
        (dsub)                                                  ; 278
        (ddiv)                                                  ; 279
        (dload_0)                                               ; 280
        (dsub)                                                  ; 281
        (dsub)                                                  ; 282
        (dreturn)                                               ; 283
        ; line_number #1013
        (dconst_1)                                              ; 284
        (dload 6)                                               ; 285
        (dload_0)                                               ; 287
        (dload 8)                                               ; 288
        (dmul)                                                  ; 290
        (ldc2_w 37)                                             ; 291 2.0d
        (dload 8)                                               ; 294
        (dsub)                                                  ; 296
        (ddiv)                                                  ; 297
        (dsub)                                                  ; 298
        (dload 4)                                               ; 299
        (dsub)                                                  ; 301
        (dsub)                                                  ; 302
        (dstore_2)                                              ; 303
        ; line_number #1015
        (iload 12)                                              ; 304
        (sipush -1021)                                          ; 306
        (if_icmplt 20)                                          ; 309
        ; line_number #1016
        (dload_2)                                               ; 312
        (dload_2)                                               ; 313
        (invokestatic 4)                                        ; 314 FdlibmTranslit.access$000:(D)I
        (iload 12)                                              ; 317
        (bipush 20)                                             ; 319
        (ishl)                                                  ; 321
        (iadd)                                                  ; 322
        (invokestatic 39)                                       ; 323 FdlibmTranslit.access$400:(DI)D
        (dstore_2)                                              ; 326
        ; line_number #1018
        (dload_2)                                               ; 327
        (dreturn)                                               ; 328
        ; line_number #1020
        (dload_2)                                               ; 329
        (dload_2)                                               ; 330
        (invokestatic 4)                                        ; 331 FdlibmTranslit.access$000:(D)I
        (iload 12)                                              ; 334
        (sipush 1000)                                           ; 336
        (iadd)                                                  ; 339
        (bipush 20)                                             ; 340
        (ishl)                                                  ; 342
        (iadd)                                                  ; 343
        (invokestatic 39)                                       ; 344 FdlibmTranslit.access$400:(DI)D
        (dstore_2)                                              ; 347
        ; line_number #1021
        (dload_2)                                               ; 348
        (ldc2_w 40)                                             ; 349 9.332636185032189E-302d
        (dmul)                                                  ; 352
        (dreturn)                                               ; 353
       )
      '("<clinit>:()V" nil
        ; line_number #934
        (iconst_2)                                              ; 0
        (newarray T_DOUBLE)                                     ; 1
        (dup)                                                   ; 3
        (iconst_0)                                              ; 4
        (ldc2_w 42)                                             ; 5 0.5d
        (dastore)                                               ; 8
        (dup)                                                   ; 9
        (iconst_1)                                              ; 10
        (ldc2_w 44)                                             ; 11 -0.5d
        (dastore)                                               ; 14
        (putstatic 23)                                          ; 15 FdlibmTranslit$Exp.halF:[D
        ; line_number #939
        (iconst_2)                                              ; 18
        (newarray T_DOUBLE)                                     ; 19
        (dup)                                                   ; 21
        (iconst_0)                                              ; 22
        (ldc2_w 46)                                             ; 23 0.6931471803691238d
        (dastore)                                               ; 26
        (dup)                                                   ; 27
        (iconst_1)                                              ; 28
        (ldc2_w 48)                                             ; 29 -0.6931471803691238d
        (dastore)                                               ; 32
        (putstatic 19)                                          ; 33 FdlibmTranslit$Exp.ln2HI:[D
        ; line_number #942
        (iconst_2)                                              ; 36
        (newarray T_DOUBLE)                                     ; 37
        (dup)                                                   ; 39
        (iconst_0)                                              ; 40
        (ldc2_w 50)                                             ; 41 1.9082149292705877E-10d
        (dastore)                                               ; 44
        (dup)                                                   ; 45
        (iconst_1)                                              ; 46
        (ldc2_w 52)                                             ; 47 -1.9082149292705877E-10d
        (dastore)                                               ; 50
        (putstatic 20)                                          ; 51 FdlibmTranslit$Exp.ln2LO:[D
        (return)                                                ; 54
       ))
     '(ref -1)))