; Automatically generated by jvm2m5

(in-package "M5")
(include-book "models/jvm/m5/m5" :dir :system)

(defconst *FdlibmTranslit$Atan2*
    (make-class-decl
     "FdlibmTranslit$Atan2"
     '("java/lang/Object")
     '(nil
       (methodref "java/lang/Object" "<init>:()V" 0)            ; 1
       (methodref "FdlibmTranslit" "access$000:(D)I" 2)         ; 2
       (integer 2147483647)                                     ; 3
       (methodref "FdlibmTranslit" "access$100:(D)I" 2)         ; 4
       (integer 2146435072)                                     ; 5
       (integer 1072693248)                                     ; 6
       (methodref "FdlibmTranslit$Atan" "compute:(D)D" 2)       ; 7
       (class (ref -1) "FdlibmTranslit$Atan2")                  ; 8
       (double #x400921fb54442d18) ; 0x1.921fb54442d18p1 3.141592653589793      ; 9
       nil
       (double #xc00921fb54442d18) ; -0x1.921fb54442d18p1 -3.141592653589793    ; 11
       nil
       (double #xbff921fb54442d18) ; -0x1.921fb54442d18p0 -1.5707963267948966   ; 13
       nil
       (double #x3ff921fb54442d18) ; 0x1.921fb54442d18p0 1.5707963267948966     ; 15
       nil
       (double #x3fe921fb54442d18) ; 0x1.921fb54442d18p-1 0.7853981633974483    ; 17
       nil
       (double #xbfe921fb54442d18) ; -0x1.921fb54442d18p-1 -0.7853981633974483  ; 19
       nil
       (double #x4002d97c7f3321d2) ; 0x1.2d97c7f3321d2p1 2.356194490192345      ; 21
       nil
       (double #xc002d97c7f3321d2) ; -0x1.2d97c7f3321d2p1 -2.356194490192345    ; 23
       nil
       (double #x8000000000000000) ; -0x0.0p0 -0.0              ; 25
       nil
       (methodref "FdlibmTranslit$Fabs" "compute:(D)D" 2)       ; 27
       (integer -2147483648)                                    ; 28
       (methodref "FdlibmTranslit" "access$400:(DI)D" 3)        ; 29
       (double #x3ca1a62633145c07) ; 0x1.1a62633145c07p-53 1.2246467991473532E-16       ; 30
       nil
       (class (ref -1) "java/lang/Object")                      ; 32
       (utf8)                                                   ; 33
       (utf8)                                                   ; 34
       (utf8)                                                   ; 35
       (double #x01a56e1fc2f8f359) ; 0x1.56e1fc2f8f359p-997 1.0E-300    ; 36
       nil
       (utf8)                                                   ; 38
       (double #x0000000000000000) ; 0x0.0p0 0.0                ; 39
       nil
       (utf8)                                                   ; 41
       (utf8)                                                   ; 42
       (utf8)                                                   ; 43
       (utf8)                                                   ; 44
       (utf8)                                                   ; 45
       (utf8)                                                   ; 46
       (utf8)                                                   ; 47
       (utf8)                                                   ; 48
       (utf8)                                                   ; 49
       (utf8)                                                   ; 50
       (utf8)                                                   ; 51
       (utf8)                                                   ; 52
       (utf8)                                                   ; 53
       (name-and-type "<init>:()V")                             ; 54
       (class (ref -1) "FdlibmTranslit")                        ; 55
       (name-and-type "access$000:(D)I")                        ; 56
       (name-and-type "access$100:(D)I")                        ; 57
       (class (ref -1) "FdlibmTranslit$Atan")                   ; 58
       (name-and-type "compute:(D)D")                           ; 59
       (utf8)                                                   ; 60
       (utf8)                                                   ; 61
       (utf8)                                                   ; 62
       (class (ref -1) "FdlibmTranslit$Fabs")                   ; 63
       (name-and-type "access$400:(DI)D")                       ; 64
       (utf8)                                                   ; 65
       (utf8)                                                   ; 66
       (utf8)                                                   ; 67
       (utf8)                                                   ; 68
       (utf8)                                                   ; 69
       (utf8)                                                   ; 70
       (utf8)                                                   ; 71
       (utf8)                                                   ; 72
       (utf8)                                                   ; 73
       (utf8)                                                   ; 74
       (utf8)                                                   ; 75
       (utf8)                                                   ; 76
      )
     #x00000020                                                 ; SUPER
     '(
       ("tiny:D" #x0000001a)                                    ; PRIVATE STATIC FINAL
       ("zero:D" #x0000001a)                                    ; PRIVATE STATIC FINAL
       ("pi_o_4:D" #x0000001a)                                  ; PRIVATE STATIC FINAL
       ("pi_o_2:D" #x0000001a)                                  ; PRIVATE STATIC FINAL
       ("pi:D" #x0000001a)                                      ; PRIVATE STATIC FINAL
       ("pi_lo:D" #x0000001a)                                   ; PRIVATE STATIC FINAL
      )
     (list
      '("<init>:()V" #x00000002                                 ; PRIVATE
        ; line_number #477
        (aload_0)                                               ; 0
        (invokespecial 1)                                       ; 1 java.lang.Object.<init>:()V
        (return)                                                ; 4
       )
      '("compute:(DD)D" #x00000808                              ; STATIC STRICT
        ; line_number #491
        (dload_2)                                               ; 0
        (invokestatic 2)                                        ; 1 FdlibmTranslit.access$000:(D)I
        (istore 8)                                              ; 4
        ; line_number #492
        (iload 8)                                               ; 6
        (ldc 3)                                                 ; 8 2147483647
        (iand)                                                  ; 10
        (istore 10)                                             ; 11
        ; line_number #493
        (dload_2)                                               ; 13
        (invokestatic 4)                                        ; 14 FdlibmTranslit.access$100:(D)I
        (istore 12)                                             ; 17
        ; line_number #494
        (dload_0)                                               ; 19
        (invokestatic 2)                                        ; 20 FdlibmTranslit.access$000:(D)I
        (istore 9)                                              ; 23
        ; line_number #495
        (iload 9)                                               ; 25
        (ldc 3)                                                 ; 27 2147483647
        (iand)                                                  ; 29
        (istore 11)                                             ; 30
        ; line_number #496
        (dload_0)                                               ; 32
        (invokestatic 4)                                        ; 33 FdlibmTranslit.access$100:(D)I
        (istore 13)                                             ; 36
        ; line_number #497
        (iload 10)                                              ; 38
        (iload 12)                                              ; 40
        (iload 12)                                              ; 42
        (ineg)                                                  ; 44
        (ior)                                                   ; 45
        (bipush 31)                                             ; 46
        (ishr)                                                  ; 48
        (ior)                                                   ; 49
        (ldc 5)                                                 ; 50 2146435072
        (if_icmpgt 20)                                          ; 52
        (iload 11)                                              ; 55
        (iload 13)                                              ; 57
        (iload 13)                                              ; 59
        (ineg)                                                  ; 61
        (ior)                                                   ; 62
        (bipush 31)                                             ; 63
        (ishr)                                                  ; 65
        (ior)                                                   ; 66
        (ldc 5)                                                 ; 67 2146435072
        (if_icmple 7)                                           ; 69
        ; line_number #499
        (dload_2)                                               ; 72
        (dload_0)                                               ; 73
        (dadd)                                                  ; 74
        (dreturn)                                               ; 75
        ; line_number #501
        (iload 8)                                               ; 76
        (ldc 6)                                                 ; 78 1072693248
        (isub)                                                  ; 80
        (iload 12)                                              ; 81
        (ior)                                                   ; 83
        (ifne 8)                                                ; 84
        ; line_number #502
        (dload_0)                                               ; 87
        (invokestatic 7)                                        ; 88 FdlibmTranslit$Atan.compute:(D)D
        (dreturn)                                               ; 91
        ; line_number #504
        (iload 9)                                               ; 92
        (bipush 31)                                             ; 94
        (ishr)                                                  ; 96
        (iconst_1)                                              ; 97
        (iand)                                                  ; 98
        (iload 8)                                               ; 99
        (bipush 30)                                             ; 101
        (ishr)                                                  ; 103
        (iconst_2)                                              ; 104
        (iand)                                                  ; 105
        (ior)                                                   ; 106
        (istore 7)                                              ; 107
        ; line_number #507
        (iload 11)                                              ; 109
        (iload 13)                                              ; 111
        (ior)                                                   ; 113
        (ifne 44)                                               ; 114
        ; line_number #508
        (iload 7)                                               ; 117
        (tableswitch 29 39 0 29 29 31 35)                       ; 119
        ; line_number #511
        (dload_0)                                               ; 148
        (dreturn)                                               ; 149
        ; line_number #513
        (ldc2_w 9)                                              ; 150 3.141592653589793d
        (dreturn)                                               ; 153
        ; line_number #515
        (ldc2_w 11)                                             ; 154 -3.141592653589793d
        (dreturn)                                               ; 157
        ; line_number #519
        (iload 10)                                              ; 158
        (iload 12)                                              ; 160
        (ior)                                                   ; 162
        (ifne 18)                                               ; 163
        ; line_number #520
        (iload 9)                                               ; 166
        (ifge 9)                                                ; 168
        (ldc2_w 13)                                             ; 171 -1.5707963267948966d
        (goto 6)                                                ; 174
        (ldc2_w 15)                                             ; 177 1.5707963267948966d
        (dreturn)                                               ; 180
        ; line_number #524
        (iload 10)                                              ; 181
        (ldc 5)                                                 ; 183 2146435072
        (if_icmpne 109)                                         ; 185
        ; line_number #525
        (iload 11)                                              ; 188
        (ldc 5)                                                 ; 190 2146435072
        (if_icmpne 55)                                          ; 192
        ; line_number #526
        (iload 7)                                               ; 195
        (tableswitch 31 47 0 31 35 39 43)                       ; 197
        ; line_number #528
        (ldc2_w 17)                                             ; 228 0.7853981633974483d
        (dreturn)                                               ; 231
        ; line_number #530
        (ldc2_w 19)                                             ; 232 -0.7853981633974483d
        (dreturn)                                               ; 235
        ; line_number #532
        (ldc2_w 21)                                             ; 236 2.356194490192345d
        (dreturn)                                               ; 239
        ; line_number #534
        (ldc2_w 23)                                             ; 240 -2.356194490192345d
        (dreturn)                                               ; 243
        (goto 50)                                               ; 244
        ; line_number #537
        (iload 7)                                               ; 247
        (tableswitch 31 45 0 31 33 37 41)                       ; 249
        ; line_number #539
        (dconst_0)                                              ; 280
        (dreturn)                                               ; 281
        ; line_number #542
        (ldc2_w 25)                                             ; 282 -0.0d
        (dreturn)                                               ; 285
        ; line_number #545
        (ldc2_w 9)                                              ; 286 3.141592653589793d
        (dreturn)                                               ; 289
        ; line_number #548
        (ldc2_w 11)                                             ; 290 -3.141592653589793d
        (dreturn)                                               ; 293
        ; line_number #554
        (iload 11)                                              ; 294
        (ldc 5)                                                 ; 296 2146435072
        (if_icmpne 18)                                          ; 298
        ; line_number #555
        (iload 9)                                               ; 301
        (ifge 9)                                                ; 303
        (ldc2_w 13)                                             ; 306 -1.5707963267948966d
        (goto 6)                                                ; 309
        (ldc2_w 15)                                             ; 312 1.5707963267948966d
        (dreturn)                                               ; 315
        ; line_number #559
        (iload 11)                                              ; 316
        (iload 10)                                              ; 318
        (isub)                                                  ; 320
        (bipush 20)                                             ; 321
        (ishr)                                                  ; 323
        (istore 6)                                              ; 324
        ; line_number #560
        (iload 6)                                               ; 326
        (bipush 60)                                             ; 328
        (if_icmple 11)                                          ; 330
        ; line_number #561
        (ldc2_w 15)                                             ; 333 1.5707963267948966d
        (dstore 4)                                              ; 336
        (goto 32)                                               ; 338
        ; line_number #562
        (iload 8)                                               ; 341
        (ifge 16)                                               ; 343
        (iload 6)                                               ; 346
        (bipush -60)                                            ; 348
        (if_icmpge 9)                                           ; 350
        ; line_number #563
        (dconst_0)                                              ; 353
        (dstore 4)                                              ; 354
        (goto 14)                                               ; 356
        ; line_number #565
        (dload_0)                                               ; 359
        (dload_2)                                               ; 360
        (ddiv)                                                  ; 361
        (invokestatic 27)                                       ; 362 FdlibmTranslit$Fabs.compute:(D)D
        (invokestatic 7)                                        ; 365 FdlibmTranslit$Atan.compute:(D)D
        (dstore 4)                                              ; 368
        ; line_number #567
        (iload 7)                                               ; 370
        (tableswitch 28 60 0 28 31 49)                          ; 372
        ; line_number #569
        (dload 4)                                               ; 400
        (dreturn)                                               ; 402
        ; line_number #572
        (dload 4)                                               ; 403
        (dload 4)                                               ; 405
        (invokestatic 2)                                        ; 407 FdlibmTranslit.access$000:(D)I
        (ldc 28)                                                ; 410 -2147483648
        (ixor)                                                  ; 412
        (invokestatic 29)                                       ; 413 FdlibmTranslit.access$400:(DI)D
        (dstore 4)                                              ; 416
        ; line_number #573
        (dload 4)                                               ; 418
        (dreturn)                                               ; 420
        ; line_number #576
        (ldc2_w 9)                                              ; 421 3.141592653589793d
        (dload 4)                                               ; 424
        (ldc2_w 30)                                             ; 426 1.2246467991473532E-16d
        (dsub)                                                  ; 429
        (dsub)                                                  ; 430
        (dreturn)                                               ; 431
        ; line_number #579
        (dload 4)                                               ; 432
        (ldc2_w 30)                                             ; 434 1.2246467991473532E-16d
        (dsub)                                                  ; 437
        (ldc2_w 9)                                              ; 438 3.141592653589793d
        (dsub)                                                  ; 441
        (dreturn)                                               ; 442
       ))
     '(ref -1)))