; Automatically generated by jvm2m5

(in-package "M5")
(include-book "models/jvm/m5/m5" :dir :system)

(defconst *FdlibmTranslit$Log1p*
    (make-class-decl
     "FdlibmTranslit$Log1p"
     '("java/lang/Object")
     '(nil
       (methodref "java/lang/Object" "<init>:()V" 0)            ; 1
       (methodref "FdlibmTranslit" "access$300:()D" 0)          ; 2
       (methodref "FdlibmTranslit" "access$500:()I" 0)          ; 3
       (methodref "FdlibmTranslit" "access$000:(D)I" 2)         ; 4
       (integer 2147483647)                                     ; 5
       (integer 1071284858)                                     ; 6
       (integer 1072693248)                                     ; 7
       (double #xbff0000000000000) ; -0x1.0p0 -1.0              ; 8
       nil
       (class (ref -1) "FdlibmTranslit$Log1p")                  ; 10
       (double #xfff0000000000000) ; -Infinity -Infinity        ; 11
       nil
       (integer 1042284544)                                     ; 13
       (double #x4350000000000000) ; 0x1.0p54 1.8014398509481984E16     ; 14
       nil
       (integer 1016070144)                                     ; 16
       (double #x3fe0000000000000) ; 0x1.0p-1 0.5               ; 17
       nil
       (integer -1076707645)                                    ; 19
       (integer 2146435072)                                     ; 20
       (integer 1128267776)                                     ; 21
       (integer 1048575)                                        ; 22
       (integer 434334)                                         ; 23
       (methodref "FdlibmTranslit" "access$400:(DI)D" 3)        ; 24
       (integer 1071644672)                                     ; 25
       (integer 1048576)                                        ; 26
       (double #x3dea39ef35793c76) ; 0x1.a39ef35793c76p-33 1.9082149292705877E-10       ; 27
       nil
       (double #x3fe62e42fee00000) ; 0x1.62e42feep-1 0.6931471803691238 ; 29
       nil
       (double #x3fe5555555555555) ; 0x1.5555555555555p-1 0.6666666666666666    ; 31
       nil
       (double #x4000000000000000) ; 0x1.0p1 2.0                ; 33
       nil
       (double #x3fe5555555555593) ; 0x1.5555555555593p-1 0.6666666666666735    ; 35
       nil
       (double #x3fd999999997fa04) ; 0x1.999999997fa04p-2 0.3999999999940942    ; 37
       nil
       (double #x3fd2492494229359) ; 0x1.2492494229359p-2 0.2857142874366239    ; 39
       nil
       (double #x3fcc71c51d8e78af) ; 0x1.c71c51d8e78afp-3 0.22222198432149784   ; 41
       nil
       (double #x3fc7466496cb03de) ; 0x1.7466496cb03dep-3 0.1818357216161805    ; 43
       nil
       (double #x3fc39a09d078c69f) ; 0x1.39a09d078c69fp-3 0.15313837699209373   ; 45
       nil
       (double #x3fc2f112df3e5244) ; 0x1.2f112df3e5244p-3 0.14798198605116586   ; 47
       nil
       (class (ref -1) "java/lang/Object")                      ; 49
       (utf8)                                                   ; 50
       (utf8)                                                   ; 51
       (utf8)                                                   ; 52
       (utf8)                                                   ; 53
       (utf8)                                                   ; 54
       (utf8)                                                   ; 55
       (utf8)                                                   ; 56
       (utf8)                                                   ; 57
       (utf8)                                                   ; 58
       (utf8)                                                   ; 59
       (utf8)                                                   ; 60
       (utf8)                                                   ; 61
       (utf8)                                                   ; 62
       (double #x0000000000000000) ; 0x0.0p0 0.0                ; 63
       nil
       (utf8)                                                   ; 65
       (utf8)                                                   ; 66
       (utf8)                                                   ; 67
       (utf8)                                                   ; 68
       (utf8)                                                   ; 69
       (utf8)                                                   ; 70
       (utf8)                                                   ; 71
       (utf8)                                                   ; 72
       (utf8)                                                   ; 73
       (name-and-type "<init>:()V")                             ; 74
       (class (ref -1) "FdlibmTranslit")                        ; 75
       (name-and-type "access$300:()D")                         ; 76
       (name-and-type "access$500:()I")                         ; 77
       (name-and-type "access$000:(D)I")                        ; 78
       (utf8)                                                   ; 79
       (utf8)                                                   ; 80
       (utf8)                                                   ; 81
       (name-and-type "access$400:(DI)D")                       ; 82
       (utf8)                                                   ; 83
       (utf8)                                                   ; 84
       (utf8)                                                   ; 85
       (utf8)                                                   ; 86
       (utf8)                                                   ; 87
       (utf8)                                                   ; 88
       (utf8)                                                   ; 89
       (utf8)                                                   ; 90
       (utf8)                                                   ; 91
       (utf8)                                                   ; 92
      )
     #x00000020                                                 ; SUPER
     '(
       ("ln2_hi:D" #x0000001a)                                  ; PRIVATE STATIC FINAL
       ("ln2_lo:D" #x0000001a)                                  ; PRIVATE STATIC FINAL
       ("two54:D" #x0000001a)                                   ; PRIVATE STATIC FINAL
       ("Lp1:D" #x0000001a)                                     ; PRIVATE STATIC FINAL
       ("Lp2:D" #x0000001a)                                     ; PRIVATE STATIC FINAL
       ("Lp3:D" #x0000001a)                                     ; PRIVATE STATIC FINAL
       ("Lp4:D" #x0000001a)                                     ; PRIVATE STATIC FINAL
       ("Lp5:D" #x0000001a)                                     ; PRIVATE STATIC FINAL
       ("Lp6:D" #x0000001a)                                     ; PRIVATE STATIC FINAL
       ("Lp7:D" #x0000001a)                                     ; PRIVATE STATIC FINAL
       ("zero:D" #x0000001a)                                    ; PRIVATE STATIC FINAL
      )
     (list
      '("<init>:()V" #x00000002                                 ; PRIVATE
        ; line_number #1743
        (aload_0)                                               ; 0
        (invokespecial 1)                                       ; 1 java.lang.Object.<init>:()V
        (return)                                                ; 4
       )
      '("compute:(D)D" #x00000808                               ; STATIC STRICT
        ; line_number #1758
        (invokestatic 2)                                        ; 0 FdlibmTranslit.access$300:()D
        (dstore 4)                                              ; 3
        (invokestatic 2)                                        ; 5 FdlibmTranslit.access$300:()D
        (dstore 6)                                              ; 8
        ; line_number #1759
        (invokestatic 3)                                        ; 10 FdlibmTranslit.access$500:()I
        (istore 18)                                             ; 13
        ; line_number #1761
        (dload_0)                                               ; 15
        (invokestatic 4)                                        ; 16 FdlibmTranslit.access$000:(D)I
        (istore 17)                                             ; 19
        ; line_number #1763
        (iload 17)                                              ; 21
        (ldc 5)                                                 ; 23 2147483647
        (iand)                                                  ; 25
        (istore 19)                                             ; 26
        ; line_number #1765
        (iconst_1)                                              ; 28
        (istore 16)                                             ; 29
        ; line_number #1766
        (iload 17)                                              ; 31
        (ldc 6)                                                 ; 33 1071284858
        (if_icmpge 87)                                          ; 35
        ; line_number #1768
        (iload 19)                                              ; 38
        (ldc 7)                                                 ; 40 1072693248
        (if_icmplt 23)                                          ; 42
        ; line_number #1770
        (dload_0)                                               ; 45
        (ldc2_w 8)                                              ; 46 -1.0d
        (dcmpl)                                                 ; 49
        (ifne 7)                                                ; 50
        ; line_number #1771
        (ldc2_w 11)                                             ; 53 -Infinityd
        (dreturn)                                               ; 56
        ; line_number #1773
        (dload_0)                                               ; 57
        (dload_0)                                               ; 58
        (dsub)                                                  ; 59
        (dload_0)                                               ; 60
        (dload_0)                                               ; 61
        (dsub)                                                  ; 62
        (ddiv)                                                  ; 63
        (dreturn)                                               ; 64
        ; line_number #1776
        (iload 19)                                              ; 65
        (ldc 13)                                                ; 67 1042284544
        (if_icmpge 32)                                          ; 69
        ; line_number #1778
        (ldc2_w 14)                                             ; 72 1.8014398509481984E16d
        (dload_0)                                               ; 75
        (dadd)                                                  ; 76
        (dconst_0)                                              ; 77
        (dcmpl)                                                 ; 78
        (ifle 12)                                               ; 79
        (iload 19)                                              ; 82
        (ldc 16)                                                ; 84 1016070144
        (if_icmpge 5)                                           ; 86
        ; line_number #1780
        (dload_0)                                               ; 89
        (dreturn)                                               ; 90
        ; line_number #1782
        (dload_0)                                               ; 91
        (dload_0)                                               ; 92
        (dload_0)                                               ; 93
        (dmul)                                                  ; 94
        (ldc2_w 17)                                             ; 95 0.5d
        (dmul)                                                  ; 98
        (dsub)                                                  ; 99
        (dreturn)                                               ; 100
        ; line_number #1785
        (iload 17)                                              ; 101
        (ifgt 10)                                               ; 103
        (iload 17)                                              ; 106
        (ldc 19)                                                ; 108 -1076707645
        (if_icmpgt 12)                                          ; 110
        ; line_number #1786
        (iconst_0)                                              ; 113
        (istore 16)                                             ; 114
        ; line_number #1787
        (dload_0)                                               ; 116
        (dstore 4)                                              ; 117
        ; line_number #1788
        (iconst_1)                                              ; 119
        (istore 18)                                             ; 120
        ; line_number #1792
        (iload 17)                                              ; 122
        (ldc 20)                                                ; 124 2146435072
        (if_icmplt 7)                                           ; 126
        ; line_number #1793
        (dload_0)                                               ; 129
        (dload_0)                                               ; 130
        (dadd)                                                  ; 131
        (dreturn)                                               ; 132
        ; line_number #1795
        (iload 16)                                              ; 133
        (ifeq 148)                                              ; 135
        ; line_number #1796
        (iload 17)                                              ; 138
        (ldc 21)                                                ; 140 1128267776
        (if_icmpge 58)                                          ; 142
        ; line_number #1797
        (dconst_1)                                              ; 145
        (dload_0)                                               ; 146
        (dadd)                                                  ; 147
        (dstore 14)                                             ; 148
        ; line_number #1798
        (dload 14)                                              ; 150
        (invokestatic 4)                                        ; 152 FdlibmTranslit.access$000:(D)I
        (istore 18)                                             ; 155
        ; line_number #1800
        (iload 18)                                              ; 157
        (bipush 20)                                             ; 159
        (ishr)                                                  ; 161
        (sipush 1023)                                           ; 162
        (isub)                                                  ; 165
        (istore 16)                                             ; 166
        ; line_number #1801
        (iload 16)                                              ; 168
        (ifle 12)                                               ; 170
        (dconst_1)                                              ; 173
        (dload 14)                                              ; 174
        (dload_0)                                               ; 176
        (dsub)                                                  ; 177
        (dsub)                                                  ; 178
        (goto 9)                                                ; 179
        (dload_0)                                               ; 182
        (dload 14)                                              ; 183
        (dconst_1)                                              ; 185
        (dsub)                                                  ; 186
        (dsub)                                                  ; 187
        (dstore 6)                                              ; 188
        ; line_number #1802
        (dload 6)                                               ; 190
        (dload 14)                                              ; 192
        (ddiv)                                                  ; 194
        (dstore 6)                                              ; 195
        (goto 27)                                               ; 197
        ; line_number #1804
        (dload_0)                                               ; 200
        (dstore 14)                                             ; 201
        ; line_number #1805
        (dload 14)                                              ; 203
        (invokestatic 4)                                        ; 205 FdlibmTranslit.access$000:(D)I
        (istore 18)                                             ; 208
        ; line_number #1807
        (iload 18)                                              ; 210
        (bipush 20)                                             ; 212
        (ishr)                                                  ; 214
        (sipush 1023)                                           ; 215
        (isub)                                                  ; 218
        (istore 16)                                             ; 219
        ; line_number #1808
        (dconst_0)                                              ; 221
        (dstore 6)                                              ; 222
        ; line_number #1810
        (iload 18)                                              ; 224
        (ldc 22)                                                ; 226 1048575
        (iand)                                                  ; 228
        (istore 18)                                             ; 229
        ; line_number #1811
        (iload 18)                                              ; 231
        (ldc 23)                                                ; 233 434334
        (if_icmpge 18)                                          ; 235
        ; line_number #1812
        (dload 14)                                              ; 238
        (iload 18)                                              ; 240
        (ldc 7)                                                 ; 242 1072693248
        (ior)                                                   ; 244
        (invokestatic 24)                                       ; 245 FdlibmTranslit.access$400:(DI)D
        (dstore 14)                                             ; 248
        (goto 27)                                               ; 250
        ; line_number #1815
        (iinc 16 1)                                             ; 253
        ; line_number #1816
        (dload 14)                                              ; 256
        (iload 18)                                              ; 258
        (ldc 25)                                                ; 260 1071644672
        (ior)                                                   ; 262
        (invokestatic 24)                                       ; 263 FdlibmTranslit.access$400:(DI)D
        (dstore 14)                                             ; 266
        ; line_number #1818
        (ldc 26)                                                ; 268 1048576
        (iload 18)                                              ; 270
        (isub)                                                  ; 272
        (iconst_2)                                              ; 273
        (ishr)                                                  ; 274
        (istore 18)                                             ; 275
        ; line_number #1820
        (dload 14)                                              ; 277
        (dconst_1)                                              ; 279
        (dsub)                                                  ; 280
        (dstore 4)                                              ; 281
        ; line_number #1822
        (ldc2_w 17)                                             ; 283 0.5d
        (dload 4)                                               ; 286
        (dmul)                                                  ; 288
        (dload 4)                                               ; 289
        (dmul)                                                  ; 291
        (dstore_2)                                              ; 292
        ; line_number #1823
        (iload 18)                                              ; 293
        (ifne 88)                                               ; 295
        ; line_number #1825
        (dload 4)                                               ; 298
        (dconst_0)                                              ; 300
        (dcmpl)                                                 ; 301
        (ifne 33)                                               ; 302
        ; line_number #1826
        (iload 16)                                              ; 305
        (ifne 5)                                                ; 307
        ; line_number #1827
        (dconst_0)                                              ; 310
        (dreturn)                                               ; 311
        ; line_number #1829
        (dload 6)                                               ; 312
        (iload 16)                                              ; 314
        (i2d)                                                   ; 316
        (ldc2_w 27)                                             ; 317 1.9082149292705877E-10d
        (dmul)                                                  ; 320
        (dadd)                                                  ; 321
        (dstore 6)                                              ; 322
        ; line_number #1830
        (iload 16)                                              ; 324
        (i2d)                                                   ; 326
        (ldc2_w 29)                                             ; 327 0.6931471803691238d
        (dmul)                                                  ; 330
        (dload 6)                                               ; 331
        (dadd)                                                  ; 333
        (dreturn)                                               ; 334
        ; line_number #1833
        (dload_2)                                               ; 335
        (dconst_1)                                              ; 336
        (ldc2_w 31)                                             ; 337 0.6666666666666666d
        (dload 4)                                               ; 340
        (dmul)                                                  ; 342
        (dsub)                                                  ; 343
        (dmul)                                                  ; 344
        (dstore 12)                                             ; 345
        ; line_number #1834
        (iload 16)                                              ; 347
        (ifne 9)                                                ; 349
        ; line_number #1835
        (dload 4)                                               ; 352
        (dload 12)                                              ; 354
        (dsub)                                                  ; 356
        (dreturn)                                               ; 357
        ; line_number #1837
        (iload 16)                                              ; 358
        (i2d)                                                   ; 360
        (ldc2_w 29)                                             ; 361 0.6931471803691238d
        (dmul)                                                  ; 364
        (dload 12)                                              ; 365
        (iload 16)                                              ; 367
        (i2d)                                                   ; 369
        (ldc2_w 27)                                             ; 370 1.9082149292705877E-10d
        (dmul)                                                  ; 373
        (dload 6)                                               ; 374
        (dadd)                                                  ; 376
        (dsub)                                                  ; 377
        (dload 4)                                               ; 378
        (dsub)                                                  ; 380
        (dsub)                                                  ; 381
        (dreturn)                                               ; 382
        ; line_number #1840
        (dload 4)                                               ; 383
        (ldc2_w 33)                                             ; 385 2.0d
        (dload 4)                                               ; 388
        (dadd)                                                  ; 390
        (ddiv)                                                  ; 391
        (dstore 8)                                              ; 392
        ; line_number #1841
        (dload 8)                                               ; 394
        (dload 8)                                               ; 396
        (dmul)                                                  ; 398
        (dstore 10)                                             ; 399
        ; line_number #1842
        (dload 10)                                              ; 401
        (ldc2_w 35)                                             ; 403 0.6666666666666735d
        (dload 10)                                              ; 406
        (ldc2_w 37)                                             ; 408 0.3999999999940942d
        (dload 10)                                              ; 411
        (ldc2_w 39)                                             ; 413 0.2857142874366239d
        (dload 10)                                              ; 416
        (ldc2_w 41)                                             ; 418 0.22222198432149784d
        (dload 10)                                              ; 421
        (ldc2_w 43)                                             ; 423 0.1818357216161805d
        (dload 10)                                              ; 426
        (ldc2_w 45)                                             ; 428 0.15313837699209373d
        (dload 10)                                              ; 431
        (ldc2_w 47)                                             ; 433 0.14798198605116586d
        (dmul)                                                  ; 436
        (dadd)                                                  ; 437
        (dmul)                                                  ; 438
        (dadd)                                                  ; 439
        (dmul)                                                  ; 440
        (dadd)                                                  ; 441
        (dmul)                                                  ; 442
        (dadd)                                                  ; 443
        (dmul)                                                  ; 444
        (dadd)                                                  ; 445
        (dmul)                                                  ; 446
        (dadd)                                                  ; 447
        (dmul)                                                  ; 448
        (dstore 12)                                             ; 449
        ; line_number #1843
        (iload 16)                                              ; 451
        (ifne 16)                                               ; 453
        ; line_number #1844
        (dload 4)                                               ; 456
        (dload_2)                                               ; 458
        (dload 8)                                               ; 459
        (dload_2)                                               ; 461
        (dload 12)                                              ; 462
        (dadd)                                                  ; 464
        (dmul)                                                  ; 465
        (dsub)                                                  ; 466
        (dsub)                                                  ; 467
        (dreturn)                                               ; 468
        ; line_number #1846
        (iload 16)                                              ; 469
        (i2d)                                                   ; 471
        (ldc2_w 29)                                             ; 472 0.6931471803691238d
        (dmul)                                                  ; 475
        (dload_2)                                               ; 476
        (dload 8)                                               ; 477
        (dload_2)                                               ; 479
        (dload 12)                                              ; 480
        (dadd)                                                  ; 482
        (dmul)                                                  ; 483
        (iload 16)                                              ; 484
        (i2d)                                                   ; 486
        (ldc2_w 27)                                             ; 487 1.9082149292705877E-10d
        (dmul)                                                  ; 490
        (dload 6)                                               ; 491
        (dadd)                                                  ; 493
        (dadd)                                                  ; 494
        (dsub)                                                  ; 495
        (dload 4)                                               ; 496
        (dsub)                                                  ; 498
        (dsub)                                                  ; 499
        (dreturn)                                               ; 500
       ))
     '(ref -1)))