; Automatically generated by jvm2m5

(in-package "M5")
(include-book "models/jvm/m5/m5" :dir :system)

(defconst *FdlibmTranslitN$Exp*
    (make-class-decl
     "FdlibmTranslitN$Exp"
     '("java/lang/Object")
     '(nil
       (methodref "java/lang/Object" "<init>:()V" 0)            ; 1
       (fieldref "FdlibmTranslitN" "U_DOUBLE:D" 2)              ; 2
       (fieldref "FdlibmTranslitN" "U_INT:I" 1)                 ; 3
       (methodref "FdlibmTranslitN" "access$000:(D)I" 2)        ; 4
       (integer 2147483647)                                     ; 5
       (integer 1082535490)                                     ; 6
       (methodref "java/lang/Integer" "compareUnsigned:(II)I" 2)        ; 7
       (integer 2146435072)                                     ; 8
       (integer 1048575)                                        ; 9
       (methodref "FdlibmTranslitN" "access$100:(D)I" 2)        ; 10
       (class (ref -1) "FdlibmTranslitN$Exp")                   ; 11
       (double #x40862e42fefa39ef) ; 0x1.62e42fefa39efp9 709.782712893384       ; 12
       nil
       (double #x7ff0000000000000) ; Infinity Infinity          ; 14
       nil
       (double #xc0874910d52d3051) ; -0x1.74910d52d3051p9 -745.1332191019411    ; 16
       nil
       (integer 1071001154)                                     ; 18
       (integer 1072734898)                                     ; 19
       (fieldref "FdlibmTranslitN$Exp" "ln2HI:[D" 1)            ; 20
       (fieldref "FdlibmTranslitN$Exp" "ln2LO:[D" 1)            ; 21
       (double #x3ff71547652b82fe) ; 0x1.71547652b82fep0 1.4426950408889634     ; 22
       nil
       (fieldref "FdlibmTranslitN$Exp" "halF:[D" 1)             ; 24
       (integer 1043333120)                                     ; 25
       (double #x7e37e43c8800759c) ; 0x1.7e43c8800759cp996 1.0E300      ; 26
       nil
       (double #x3fc555555555553e) ; 0x1.555555555553ep-3 0.16666666666666602   ; 28
       nil
       (double #xbf66c16c16bebd93) ; -0x1.6c16c16bebd93p-9 -0.0027777777777015593       ; 30
       nil
       (double #x3f11566aaf25de2c) ; 0x1.1566aaf25de2cp-14 6.613756321437934E-5 ; 32
       nil
       (double #xbebbbd41c5d26bf1) ; -0x1.bbd41c5d26bf1p-20 -1.6533902205465252E-6      ; 34
       nil
       (double #x3e66376972bea4d0) ; 0x1.6376972bea4dp-25 4.1381367970572385E-8 ; 36
       nil
       (double #x4000000000000000) ; 0x1.0p1 2.0                ; 38
       nil
       (methodref "FdlibmTranslitN" "access$300:(DI)D" 3)       ; 40
       (double #x0170000000000000) ; 0x1.0p-1000 9.332636185032189E-302 ; 41
       nil
       (double #x3fe0000000000000) ; 0x1.0p-1 0.5               ; 43
       nil
       (double #xbfe0000000000000) ; -0x1.0p-1 -0.5             ; 45
       nil
       (double #x3fe62e42fee00000) ; 0x1.62e42feep-1 0.6931471803691238 ; 47
       nil
       (double #xbfe62e42fee00000) ; -0x1.62e42feep-1 -0.6931471803691238       ; 49
       nil
       (double #x3dea39ef35793c76) ; 0x1.a39ef35793c76p-33 1.9082149292705877E-10       ; 51
       nil
       (double #xbdea39ef35793c76) ; -0x1.a39ef35793c76p-33 -1.9082149292705877E-10     ; 53
       nil
       (class (ref -1) "java/lang/Object")                      ; 55
       (utf8)                                                   ; 56
       (utf8)                                                   ; 57
       (utf8)                                                   ; 58
       (double #x3ff0000000000000) ; 0x1.0p0 1.0                ; 59
       nil
       (utf8)                                                   ; 61
       (utf8)                                                   ; 62
       (utf8)                                                   ; 63
       (utf8)                                                   ; 64
       (utf8)                                                   ; 65
       (utf8)                                                   ; 66
       (utf8)                                                   ; 67
       (utf8)                                                   ; 68
       (utf8)                                                   ; 69
       (utf8)                                                   ; 70
       (utf8)                                                   ; 71
       (utf8)                                                   ; 72
       (utf8)                                                   ; 73
       (utf8)                                                   ; 74
       (utf8)                                                   ; 75
       (utf8)                                                   ; 76
       (utf8)                                                   ; 77
       (utf8)                                                   ; 78
       (utf8)                                                   ; 79
       (utf8)                                                   ; 80
       (utf8)                                                   ; 81
       (utf8)                                                   ; 82
       (utf8)                                                   ; 83
       (utf8)                                                   ; 84
       (name-and-type "<init>:()V")                             ; 85
       (class (ref -1) "FdlibmTranslitN")                       ; 86
       (name-and-type "U_DOUBLE:D")                             ; 87
       (name-and-type "U_INT:I")                                ; 88
       (name-and-type "access$000:(D)I")                        ; 89
       (class (ref -1) "java/lang/Integer")                     ; 90
       (name-and-type "compareUnsigned:(II)I")                  ; 91
       (name-and-type "access$100:(D)I")                        ; 92
       (utf8)                                                   ; 93
       (utf8)                                                   ; 94
       (utf8)                                                   ; 95
       (name-and-type "ln2HI:[D")                               ; 96
       (name-and-type "ln2LO:[D")                               ; 97
       (name-and-type "halF:[D")                                ; 98
       (name-and-type "access$300:(DI)D")                       ; 99
       (utf8)                                                   ; 100
       (utf8)                                                   ; 101
       (utf8)                                                   ; 102
       (utf8)                                                   ; 103
       (utf8)                                                   ; 104
       (utf8)                                                   ; 105
       (utf8)                                                   ; 106
       (utf8)                                                   ; 107
       (utf8)                                                   ; 108
       (utf8)                                                   ; 109
       (utf8)                                                   ; 110
       (utf8)                                                   ; 111
       (utf8)                                                   ; 112
      )
     #x00000020                                                 ; SUPER
     '(
       ("one:D" #x00000018)                                     ; STATIC FINAL
       ("halF:[D" #x00000018)                                   ; STATIC FINAL
       ("huge:D" #x00000018)                                    ; STATIC FINAL
       ("twom1000:D" #x00000018)                                ; STATIC FINAL
       ("o_threshold:D" #x00000018)                             ; STATIC FINAL
       ("u_threshold:D" #x00000018)                             ; STATIC FINAL
       ("ln2HI:[D" #x00000018)                                  ; STATIC FINAL
       ("ln2LO:[D" #x00000018)                                  ; STATIC FINAL
       ("invln2:D" #x00000018)                                  ; STATIC FINAL
       ("P1:D" #x00000018)                                      ; STATIC FINAL
       ("P2:D" #x00000018)                                      ; STATIC FINAL
       ("P3:D" #x00000018)                                      ; STATIC FINAL
       ("P4:D" #x00000018)                                      ; STATIC FINAL
       ("P5:D" #x00000018)                                      ; STATIC FINAL
      )
     (list
      '("<init>:()V" #x00000002                                 ; PRIVATE
        ; line_number #1043
        (aload_0)                                               ; 0
        (invokespecial 1)                                       ; 1 java.lang.Object.<init>:()V
        (return)                                                ; 4
       )
      '("compute:(D)D" #x00000808                               ; STATIC STRICT
        ; line_number #1070
        (getstatic 2)                                           ; 0 FdlibmTranslitN.U_DOUBLE:D
        (dstore 4)                                              ; 3
        (getstatic 2)                                           ; 5 FdlibmTranslitN.U_DOUBLE:D
        (dstore 6)                                              ; 8
        ; line_number #1071
        (getstatic 3)                                           ; 10 FdlibmTranslitN.U_INT:I
        (istore 12)                                             ; 13
        ; line_number #1074
        (dload_0)                                               ; 15
        (invokestatic 4)                                        ; 16 FdlibmTranslitN.access$000:(D)I
        (istore 14)                                             ; 19
        ; line_number #1075
        (iload 14)                                              ; 21
        (bipush 31)                                             ; 23
        (iushr)                                                 ; 25
        (iconst_1)                                              ; 26
        (iand)                                                  ; 27
        (istore 13)                                             ; 28
        ; line_number #1076
        (iload 14)                                              ; 30
        (ldc 5)                                                 ; 32 2147483647
        (iand)                                                  ; 34
        (istore 14)                                             ; 35
        ; line_number #1079
        (iload 14)                                              ; 37
        (ldc 6)                                                 ; 39 1082535490
        (invokestatic 7)                                        ; 41 java.lang.Integer.compareUnsigned:(II)I
        (iflt 63)                                               ; 44
        ; line_number #1080
        (iload 14)                                              ; 47
        (ldc 8)                                                 ; 49 2146435072
        (invokestatic 7)                                        ; 51 java.lang.Integer.compareUnsigned:(II)I
        (iflt 31)                                               ; 54
        ; line_number #1081
        (iload 14)                                              ; 57
        (ldc 9)                                                 ; 59 1048575
        (iand)                                                  ; 61
        (dload_0)                                               ; 62
        (invokestatic 10)                                       ; 63 FdlibmTranslitN.access$100:(D)I
        (ior)                                                   ; 66
        (ifeq 7)                                                ; 67
        ; line_number #1082
        (dload_0)                                               ; 70
        (dload_0)                                               ; 71
        (dadd)                                                  ; 72
        (dreturn)                                               ; 73
        ; line_number #1083
        (iload 13)                                              ; 74
        (ifne 7)                                                ; 76
        (dload_0)                                               ; 79
        (goto 4)                                                ; 80
        (dconst_0)                                              ; 83
        (dreturn)                                               ; 84
        ; line_number #1085
        (dload_0)                                               ; 85
        (ldc2_w 12)                                             ; 86 709.782712893384d
        (dcmpl)                                                 ; 89
        (ifle 7)                                                ; 90
        (ldc2_w 14)                                             ; 93 Infinityd
        (dreturn)                                               ; 96
        ; line_number #1086
        (dload_0)                                               ; 97
        (ldc2_w 16)                                             ; 98 -745.1332191019411d
        (dcmpg)                                                 ; 101
        (ifge 5)                                                ; 102
        (dconst_0)                                              ; 105
        (dreturn)                                               ; 106
        ; line_number #1090
        (iload 14)                                              ; 107
        (ldc 18)                                                ; 109 1071001154
        (invokestatic 7)                                        ; 111 java.lang.Integer.compareUnsigned:(II)I
        (ifle 94)                                               ; 114
        ; line_number #1091
        (iload 14)                                              ; 117
        (ldc 19)                                                ; 119 1072734898
        (invokestatic 7)                                        ; 121 java.lang.Integer.compareUnsigned:(II)I
        (ifge 33)                                               ; 124
        ; line_number #1092
        (dload_0)                                               ; 127
        (getstatic 20)                                          ; 128 FdlibmTranslitN$Exp.ln2HI:[D
        (iload 13)                                              ; 131
        (daload)                                                ; 133
        (dsub)                                                  ; 134
        (dstore 4)                                              ; 135
        (getstatic 21)                                          ; 137 FdlibmTranslitN$Exp.ln2LO:[D
        (iload 13)                                              ; 140
        (daload)                                                ; 142
        (dstore 6)                                              ; 143
        (iconst_1)                                              ; 145
        (iload 13)                                              ; 146
        (isub)                                                  ; 148
        (iload 13)                                              ; 149
        (isub)                                                  ; 151
        (istore 12)                                             ; 152
        (goto 45)                                               ; 154
        ; line_number #1094
        (ldc2_w 22)                                             ; 157 1.4426950408889634d
        (dload_0)                                               ; 160
        (dmul)                                                  ; 161
        (getstatic 24)                                          ; 162 FdlibmTranslitN$Exp.halF:[D
        (iload 13)                                              ; 165
        (daload)                                                ; 167
        (dadd)                                                  ; 168
        (d2i)                                                   ; 169
        (istore 12)                                             ; 170
        ; line_number #1095
        (iload 12)                                              ; 172
        (i2d)                                                   ; 174
        (dstore 10)                                             ; 175
        ; line_number #1096
        (dload_0)                                               ; 177
        (dload 10)                                              ; 178
        (getstatic 20)                                          ; 180 FdlibmTranslitN$Exp.ln2HI:[D
        (iconst_0)                                              ; 183
        (daload)                                                ; 184
        (dmul)                                                  ; 185
        (dsub)                                                  ; 186
        (dstore 4)                                              ; 187
        ; line_number #1097
        (dload 10)                                              ; 189
        (getstatic 21)                                          ; 191 FdlibmTranslitN$Exp.ln2LO:[D
        (iconst_0)                                              ; 194
        (daload)                                                ; 195
        (dmul)                                                  ; 196
        (dstore 6)                                              ; 197
        ; line_number #1099
        (dload 4)                                               ; 199
        (dload 6)                                               ; 201
        (dsub)                                                  ; 203
        (dstore_0)                                              ; 204
        (goto 30)                                               ; 205
        ; line_number #1101
        (iload 14)                                              ; 208
        (ldc 25)                                                ; 210 1043333120
        (invokestatic 7)                                        ; 212 java.lang.Integer.compareUnsigned:(II)I
        (ifge 17)                                               ; 215
        ; line_number #1102
        (ldc2_w 26)                                             ; 218 1.0E300d
        (dload_0)                                               ; 221
        (dadd)                                                  ; 222
        (dconst_1)                                              ; 223
        (dcmpl)                                                 ; 224
        (ifle 10)                                               ; 225
        (dconst_1)                                              ; 228
        (dload_0)                                               ; 229
        (dadd)                                                  ; 230
        (dreturn)                                               ; 231
        ; line_number #1104
        (iconst_0)                                              ; 232
        (istore 12)                                             ; 233
        ; line_number #1107
        (dload_0)                                               ; 235
        (dload_0)                                               ; 236
        (dmul)                                                  ; 237
        (dstore 10)                                             ; 238
        ; line_number #1108
        (dload_0)                                               ; 240
        (dload 10)                                              ; 241
        (ldc2_w 28)                                             ; 243 0.16666666666666602d
        (dload 10)                                              ; 246
        (ldc2_w 30)                                             ; 248 -0.0027777777777015593d
        (dload 10)                                              ; 251
        (ldc2_w 32)                                             ; 253 6.613756321437934E-5d
        (dload 10)                                              ; 256
        (ldc2_w 34)                                             ; 258 -1.6533902205465252E-6d
        (dload 10)                                              ; 261
        (ldc2_w 36)                                             ; 263 4.1381367970572385E-8d
        (dmul)                                                  ; 266
        (dadd)                                                  ; 267
        (dmul)                                                  ; 268
        (dadd)                                                  ; 269
        (dmul)                                                  ; 270
        (dadd)                                                  ; 271
        (dmul)                                                  ; 272
        (dadd)                                                  ; 273
        (dmul)                                                  ; 274
        (dsub)                                                  ; 275
        (dstore 8)                                              ; 276
        ; line_number #1109
        (iload 12)                                              ; 278
        (ifne 19)                                               ; 280
        (dconst_1)                                              ; 283
        (dload_0)                                               ; 284
        (dload 8)                                               ; 285
        (dmul)                                                  ; 287
        (dload 8)                                               ; 288
        (ldc2_w 38)                                             ; 290 2.0d
        (dsub)                                                  ; 293
        (ddiv)                                                  ; 294
        (dload_0)                                               ; 295
        (dsub)                                                  ; 296
        (dsub)                                                  ; 297
        (dreturn)                                               ; 298
        ; line_number #1110
        (dconst_1)                                              ; 299
        (dload 6)                                               ; 300
        (dload_0)                                               ; 302
        (dload 8)                                               ; 303
        (dmul)                                                  ; 305
        (ldc2_w 38)                                             ; 306 2.0d
        (dload 8)                                               ; 309
        (dsub)                                                  ; 311
        (ddiv)                                                  ; 312
        (dsub)                                                  ; 313
        (dload 4)                                               ; 314
        (dsub)                                                  ; 316
        (dsub)                                                  ; 317
        (dstore_2)                                              ; 318
        ; line_number #1111
        (iload 12)                                              ; 319
        (sipush -1021)                                          ; 321
        (if_icmplt 20)                                          ; 324
        ; line_number #1112
        (dload_2)                                               ; 327
        (dload_2)                                               ; 328
        (invokestatic 4)                                        ; 329 FdlibmTranslitN.access$000:(D)I
        (iload 12)                                              ; 332
        (bipush 20)                                             ; 334
        (ishl)                                                  ; 336
        (iadd)                                                  ; 337
        (invokestatic 40)                                       ; 338 FdlibmTranslitN.access$300:(DI)D
        (dstore_2)                                              ; 341
        ; line_number #1113
        (dload_2)                                               ; 342
        (dreturn)                                               ; 343
        ; line_number #1115
        (dload_2)                                               ; 344
        (dload_2)                                               ; 345
        (invokestatic 4)                                        ; 346 FdlibmTranslitN.access$000:(D)I
        (iload 12)                                              ; 349
        (sipush 1000)                                           ; 351
        (iadd)                                                  ; 354
        (bipush 20)                                             ; 355
        (ishl)                                                  ; 357
        (iadd)                                                  ; 358
        (invokestatic 40)                                       ; 359 FdlibmTranslitN.access$300:(DI)D
        (dstore_2)                                              ; 362
        ; line_number #1116
        (dload_2)                                               ; 363
        (ldc2_w 41)                                             ; 364 9.332636185032189E-302d
        (dmul)                                                  ; 367
        (dreturn)                                               ; 368
       )
      '("<clinit>:()V" #x00000008                               ; STATIC
        ; line_number #1049
        (iconst_2)                                              ; 0
        (newarray T_DOUBLE)                                     ; 1
        (dup)                                                   ; 3
        (iconst_0)                                              ; 4
        (ldc2_w 43)                                             ; 5 0.5d
        (dastore)                                               ; 8
        (dup)                                                   ; 9
        (iconst_1)                                              ; 10
        (ldc2_w 45)                                             ; 11 -0.5d
        (dastore)                                               ; 14
        (putstatic 24)                                          ; 15 FdlibmTranslitN$Exp.halF:[D
        ; line_number #1054
        (iconst_2)                                              ; 18
        (newarray T_DOUBLE)                                     ; 19
        (dup)                                                   ; 21
        (iconst_0)                                              ; 22
        (ldc2_w 47)                                             ; 23 0.6931471803691238d
        (dastore)                                               ; 26
        (dup)                                                   ; 27
        (iconst_1)                                              ; 28
        (ldc2_w 49)                                             ; 29 -0.6931471803691238d
        (dastore)                                               ; 32
        (putstatic 20)                                          ; 33 FdlibmTranslitN$Exp.ln2HI:[D
        ; line_number #1056
        (iconst_2)                                              ; 36
        (newarray T_DOUBLE)                                     ; 37
        (dup)                                                   ; 39
        (iconst_0)                                              ; 40
        (ldc2_w 51)                                             ; 41 1.9082149292705877E-10d
        (dastore)                                               ; 44
        (dup)                                                   ; 45
        (iconst_1)                                              ; 46
        (ldc2_w 53)                                             ; 47 -1.9082149292705877E-10d
        (dastore)                                               ; 50
        (putstatic 21)                                          ; 51 FdlibmTranslitN$Exp.ln2LO:[D
        (return)                                                ; 54
       ))
     '(ref -1)))