; Automatically generated by jvm2m5

(in-package "M5")
(include-book "models/jvm/m5/m5" :dir :system)

(defconst *FdlibmTranslitN$Sinh*
    (make-class-decl
     "FdlibmTranslitN$Sinh"
     '("java/lang/Object")
     '(nil
       (methodref "java/lang/Object" "<init>:()V" 0)            ; 1
       (methodref "FdlibmTranslitN" "access$000:(D)I" 2)        ; 2
       (integer 2147483647)                                     ; 3
       (integer 2146435072)                                     ; 4
       (double #x3fe0000000000000) ; 0x1.0p-1 0.5               ; 5
       nil
       (integer 1077280768)                                     ; 7
       (integer 1043333120)                                     ; 8
       (class (ref -1) "FdlibmTranslitN$Sinh")                  ; 9
       (double #x7fac7b1f3cac7433) ; 0x1.c7b1f3cac7433p1019 1.0E307     ; 10
       nil
       (methodref "FdlibmTranslitN$Fabs" "compute:(D)D" 2)      ; 12
       (methodref "FdlibmTranslitN" "expm1:(D)D" 2)             ; 13
       (integer 1072693248)                                     ; 14
       (double #x4000000000000000) ; 0x1.0p1 2.0                ; 15
       nil
       (integer 1082535490)                                     ; 17
       (methodref "FdlibmTranslitN$Exp" "compute:(D)D" 2)       ; 18
       (methodref "FdlibmTranslitN" "access$400:(D)[I" 2)       ; 19
       (integer 1082536910)                                     ; 20
       (integer -1883637635)                                    ; 21
       (methodref "java/lang/Integer" "compareUnsigned:(II)I" 2)        ; 22
       (class (ref -1) "java/lang/Object")                      ; 23
       (utf8)                                                   ; 24
       (utf8)                                                   ; 25
       (utf8)                                                   ; 26
       (double #x3ff0000000000000) ; 0x1.0p0 1.0                ; 27
       nil
       (utf8)                                                   ; 29
       (utf8)                                                   ; 30
       (utf8)                                                   ; 31
       (utf8)                                                   ; 32
       (utf8)                                                   ; 33
       (utf8)                                                   ; 34
       (utf8)                                                   ; 35
       (utf8)                                                   ; 36
       (utf8)                                                   ; 37
       (utf8)                                                   ; 38
       (name-and-type "<init>:()V")                             ; 39
       (class (ref -1) "FdlibmTranslitN")                       ; 40
       (name-and-type "access$000:(D)I")                        ; 41
       (utf8)                                                   ; 42
       (utf8)                                                   ; 43
       (utf8)                                                   ; 44
       (class (ref -1) "FdlibmTranslitN$Fabs")                  ; 45
       (name-and-type "compute:(D)D")                           ; 46
       (name-and-type "expm1:(D)D")                             ; 47
       (class (ref -1) "FdlibmTranslitN$Exp")                   ; 48
       (name-and-type "access$400:(D)[I")                       ; 49
       (class (ref -1) "java/lang/Integer")                     ; 50
       (name-and-type "compareUnsigned:(II)I")                  ; 51
       (utf8)                                                   ; 52
       (utf8)                                                   ; 53
       (utf8)                                                   ; 54
       (utf8)                                                   ; 55
       (utf8)                                                   ; 56
       (utf8)                                                   ; 57
       (utf8)                                                   ; 58
       (utf8)                                                   ; 59
       (utf8)                                                   ; 60
       (utf8)                                                   ; 61
       (utf8)                                                   ; 62
       (utf8)                                                   ; 63
       (utf8)                                                   ; 64
       (utf8)                                                   ; 65
      )
     #x00000020                                                 ; SUPER
     '(
       ("one:D" #x00000018)                                     ; STATIC FINAL
       ("shuge:D" #x00000018)                                   ; STATIC FINAL
      )
     (list
      '("<init>:()V" #x00000002                                 ; PRIVATE
        ; line_number #2943
        (aload_0)                                               ; 0
        (invokespecial 1)                                       ; 1 java.lang.Object.<init>:()V
        (return)                                                ; 4
       )
      '("compute:(D)D" #x00000808                               ; STATIC STRICT
        ; line_number #2958
        (dload_0)                                               ; 0
        (invokestatic 2)                                        ; 1 FdlibmTranslitN.access$000:(D)I
        (istore 9)                                              ; 4
        ; line_number #2959
        (iload 9)                                               ; 6
        (ldc 3)                                                 ; 8 2147483647
        (iand)                                                  ; 10
        (istore 8)                                              ; 11
        ; line_number #2962
        (iload 8)                                               ; 13
        (ldc 4)                                                 ; 15 2146435072
        (if_icmplt 7)                                           ; 17
        (dload_0)                                               ; 20
        (dload_0)                                               ; 21
        (dadd)                                                  ; 22
        (dreturn)                                               ; 23
        ; line_number #2964
        (ldc2_w 5)                                              ; 24 0.5d
        (dstore 6)                                              ; 27
        ; line_number #2965
        (iload 9)                                               ; 29
        (ifge 8)                                                ; 31
        (dload 6)                                               ; 34
        (dneg)                                                  ; 36
        (dstore 6)                                              ; 37
        ; line_number #2967
        (iload 8)                                               ; 39
        (ldc 7)                                                 ; 41 1077280768
        (if_icmpge 65)                                          ; 43
        ; line_number #2968
        (iload 8)                                               ; 46
        (ldc 8)                                                 ; 48 1043333120
        (if_icmpge 15)                                          ; 50
        ; line_number #2969
        (ldc2_w 10)                                             ; 53 1.0E307d
        (dload_0)                                               ; 56
        (dadd)                                                  ; 57
        (dconst_1)                                              ; 58
        (dcmpl)                                                 ; 59
        (ifle 5)                                                ; 60
        (dload_0)                                               ; 63
        (dreturn)                                               ; 64
        ; line_number #2970
        (dload_0)                                               ; 65
        (invokestatic 12)                                       ; 66 FdlibmTranslitN$Fabs.compute:(D)D
        (invokestatic 13)                                       ; 69 FdlibmTranslitN.expm1:(D)D
        (dstore_2)                                              ; 72
        ; line_number #2971
        (iload 8)                                               ; 73
        (ldc 14)                                                ; 75 1072693248
        (if_icmpge 20)                                          ; 77
        (dload 6)                                               ; 80
        (ldc2_w 15)                                             ; 82 2.0d
        (dload_2)                                               ; 85
        (dmul)                                                  ; 86
        (dload_2)                                               ; 87
        (dload_2)                                               ; 88
        (dmul)                                                  ; 89
        (dload_2)                                               ; 90
        (dconst_1)                                              ; 91
        (dadd)                                                  ; 92
        (ddiv)                                                  ; 93
        (dsub)                                                  ; 94
        (dmul)                                                  ; 95
        (dreturn)                                               ; 96
        ; line_number #2972
        (dload 6)                                               ; 97
        (dload_2)                                               ; 99
        (dload_2)                                               ; 100
        (dload_2)                                               ; 101
        (dconst_1)                                              ; 102
        (dadd)                                                  ; 103
        (ddiv)                                                  ; 104
        (dadd)                                                  ; 105
        (dmul)                                                  ; 106
        (dreturn)                                               ; 107
        ; line_number #2976
        (iload 8)                                               ; 108
        (ldc 17)                                                ; 110 1082535490
        (if_icmpge 14)                                          ; 112
        (dload 6)                                               ; 115
        (dload_0)                                               ; 117
        (invokestatic 12)                                       ; 118 FdlibmTranslitN$Fabs.compute:(D)D
        (invokestatic 18)                                       ; 121 FdlibmTranslitN$Exp.compute:(D)D
        (dmul)                                                  ; 124
        (dreturn)                                               ; 125
        ; line_number #2979
        (dload_0)                                               ; 126
        (invokestatic 19)                                       ; 127 FdlibmTranslitN.access$400:(D)[I
        (dconst_1)                                              ; 130
        (invokestatic 19)                                       ; 131 FdlibmTranslitN.access$400:(D)[I
        (iconst_0)                                              ; 134
        (iaload)                                                ; 135
        (bipush 29)                                             ; 136
        (iushr)                                                 ; 138
        (iaload)                                                ; 139
        (istore 10)                                             ; 140
        ; line_number #2980
        (iload 8)                                               ; 142
        (ldc 20)                                                ; 144 1082536910
        (if_icmplt 20)                                          ; 146
        (iload 8)                                               ; 149
        (ldc 20)                                                ; 151 1082536910
        (if_icmpne 37)                                          ; 153
        (iload 10)                                              ; 156
        (ldc 21)                                                ; 158 -1883637635
        (invokestatic 22)                                       ; 160 java.lang.Integer.compareUnsigned:(II)I
        (ifgt 27)                                               ; 163
        ; line_number #2981
        (ldc2_w 5)                                              ; 166 0.5d
        (dload_0)                                               ; 169
        (invokestatic 12)                                       ; 170 FdlibmTranslitN$Fabs.compute:(D)D
        (dmul)                                                  ; 173
        (invokestatic 18)                                       ; 174 FdlibmTranslitN$Exp.compute:(D)D
        (dstore 4)                                              ; 177
        ; line_number #2982
        (dload 6)                                               ; 179
        (dload 4)                                               ; 181
        (dmul)                                                  ; 183
        (dstore_2)                                              ; 184
        ; line_number #2983
        (dload_2)                                               ; 185
        (dload 4)                                               ; 186
        (dmul)                                                  ; 188
        (dreturn)                                               ; 189
        ; line_number #2987
        (dload_0)                                               ; 190
        (ldc2_w 10)                                             ; 191 1.0E307d
        (dmul)                                                  ; 194
        (dreturn)                                               ; 195
       ))
     '(ref -1)))