; Automatically generated by jvm2m5

(in-package "M5")
(include-book "models/jvm/m5/m5" :dir :system)

(defconst *FdlibmTranslit$Cos*
    (make-class-decl
     "FdlibmTranslit$Cos"
     '("java/lang/Object")
     '(nil
       (methodref "java/lang/Object" "<init>:()V" 0)            ; 1
       (methodref "FdlibmTranslit" "access$000:(D)I" 2)         ; 2
       (integer 2147483647)                                     ; 3
       (integer 1072243195)                                     ; 4
       (methodref "FdlibmTranslit$KernelCos" "compute:(DD)D" 4) ; 5
       (integer 2146435072)                                     ; 6
       (methodref "FdlibmTranslit$RemPio2" "compute:(D[D)I" 3)  ; 7
       (methodref "FdlibmTranslit$KernelSin" "compute:(DDI)D" 5)        ; 8
       (class (ref -1) "FdlibmTranslit$Cos")                    ; 9
       (class (ref -1) "java/lang/Object")                      ; 10
       (utf8)                                                   ; 11
       (utf8)                                                   ; 12
       (utf8)                                                   ; 13
       (utf8)                                                   ; 14
       (utf8)                                                   ; 15
       (utf8)                                                   ; 16
       (utf8)                                                   ; 17
       (class (ref -1) "[D")                                    ; 18
       (utf8)                                                   ; 19
       (utf8)                                                   ; 20
       (name-and-type "<init>:()V")                             ; 21
       (class (ref -1) "FdlibmTranslit")                        ; 22
       (name-and-type "access$000:(D)I")                        ; 23
       (class (ref -1) "FdlibmTranslit$KernelCos")              ; 24
       (name-and-type "compute:(DD)D")                          ; 25
       (class (ref -1) "FdlibmTranslit$RemPio2")                ; 26
       (name-and-type "compute:(D[D)I")                         ; 27
       (class (ref -1) "FdlibmTranslit$KernelSin")              ; 28
       (name-and-type "compute:(DDI)D")                         ; 29
       (utf8)                                                   ; 30
       (utf8)                                                   ; 31
       (utf8)                                                   ; 32
       (utf8)                                                   ; 33
       (utf8)                                                   ; 34
       (utf8)                                                   ; 35
       (utf8)                                                   ; 36
       (utf8)                                                   ; 37
       (utf8)                                                   ; 38
       (utf8)                                                   ; 39
       (utf8)                                                   ; 40
       (utf8)                                                   ; 41
       (utf8)                                                   ; 42
       (utf8)                                                   ; 43
       (utf8)                                                   ; 44
       (utf8)                                                   ; 45
       (utf8)                                                   ; 46
      )
     #x00000020                                                 ; SUPER
     '(
      )
     (list
      '("<init>:()V" #x00000002                                 ; PRIVATE
        ; line_number #688
        (aload_0)                                               ; 0
        (invokespecial 1)                                       ; 1 java.lang.Object.<init>:()V
        (return)                                                ; 4
       )
      '("compute:(D)D" #x00000808                               ; STATIC STRICT
        ; line_number #691
        (iconst_2)                                              ; 0
        (newarray T_DOUBLE)                                     ; 1
        (astore_2)                                              ; 3
        (dconst_0)                                              ; 4
        (dstore_3)                                              ; 5
        ; line_number #695
        (dload_0)                                               ; 6
        (invokestatic 2)                                        ; 7 FdlibmTranslit.access$000:(D)I
        (istore 6)                                              ; 10
        ; line_number #698
        (iload 6)                                               ; 12
        (ldc 3)                                                 ; 14 2147483647
        (iand)                                                  ; 16
        (istore 6)                                              ; 17
        ; line_number #699
        (iload 6)                                               ; 19
        (ldc 4)                                                 ; 21 1072243195
        (if_icmpgt 9)                                           ; 23
        ; line_number #700
        (dload_0)                                               ; 26
        (dload_3)                                               ; 27
        (invokestatic 5)                                        ; 28 FdlibmTranslit$KernelCos.compute:(DD)D
        (dreturn)                                               ; 31
        ; line_number #701
        (iload 6)                                               ; 32
        (ldc 6)                                                 ; 34 2146435072
        (if_icmplt 7)                                           ; 36
        ; line_number #702
        (dload_0)                                               ; 39
        (dload_0)                                               ; 40
        (dsub)                                                  ; 41
        (dreturn)                                               ; 42
        ; line_number #704
        (dload_0)                                               ; 43
        (aload_2)                                               ; 44
        (invokestatic 7)                                        ; 45 FdlibmTranslit$RemPio2.compute:(D[D)I
        (istore 5)                                              ; 48
        ; line_number #705
        (iload 5)                                               ; 50
        (iconst_3)                                              ; 52
        (iand)                                                  ; 53
        (tableswitch 26 59 0 26 36 48)                          ; 54
        ; line_number #707
        (aload_2)                                               ; 80
        (iconst_0)                                              ; 81
        (daload)                                                ; 82
        (aload_2)                                               ; 83
        (iconst_1)                                              ; 84
        (daload)                                                ; 85
        (invokestatic 5)                                        ; 86 FdlibmTranslit$KernelCos.compute:(DD)D
        (dreturn)                                               ; 89
        ; line_number #709
        (aload_2)                                               ; 90
        (iconst_0)                                              ; 91
        (daload)                                                ; 92
        (aload_2)                                               ; 93
        (iconst_1)                                              ; 94
        (daload)                                                ; 95
        (iconst_1)                                              ; 96
        (invokestatic 8)                                        ; 97 FdlibmTranslit$KernelSin.compute:(DDI)D
        (dneg)                                                  ; 100
        (dreturn)                                               ; 101
        ; line_number #711
        (aload_2)                                               ; 102
        (iconst_0)                                              ; 103
        (daload)                                                ; 104
        (aload_2)                                               ; 105
        (iconst_1)                                              ; 106
        (daload)                                                ; 107
        (invokestatic 5)                                        ; 108 FdlibmTranslit$KernelCos.compute:(DD)D
        (dneg)                                                  ; 111
        (dreturn)                                               ; 112
        ; line_number #713
        (aload_2)                                               ; 113
        (iconst_0)                                              ; 114
        (daload)                                                ; 115
        (aload_2)                                               ; 116
        (iconst_1)                                              ; 117
        (daload)                                                ; 118
        (iconst_1)                                              ; 119
        (invokestatic 8)                                        ; 120 FdlibmTranslit$KernelSin.compute:(DDI)D
        (dreturn)                                               ; 123
       ))
     '(ref -1)))