; Automatically generated by jvm2m5

(in-package "M5")
(include-book "models/jvm/m5/m5" :dir :system)

(defconst *java.lang.Double*
    (make-class-decl
     "java/lang/Double"
     '("java/lang/Number")
     '(
      "value:D")
     '(
      "POSITIVE_INFINITY:D"
      "NEGATIVE_INFINITY:D"
      "NaN:D"
      "MAX_VALUE:D"
      "MIN_NORMAL:D"
      "MIN_VALUE:D"
      "MAX_EXPONENT:I"
      "MIN_EXPONENT:I"
      "SIZE:I"
      "BYTES:I"
      "TYPE:Ljava/lang/Class;"
      "serialVersionUID:J")
     '(nil
       (class (ref -1) "java/lang/Double")                     ; 1
       (class (ref -1) "java/lang/Byte")                       ; 2
       (methodref "jdk/internal/math/FloatingDecimal" "toJavaFormatString:(D)Ljava/lang/String;" 2)    ; 3
       (methodref "java/lang/Double" "isFinite:(D)Z" 2)        ; 4
       (methodref "java/lang/Double" "toString:(D)Ljava/lang/String;" 2)       ; 5
       (class (ref -1) "java/lang/StringBuilder")              ; 6
       (methodref "java/lang/StringBuilder" "<init>:(I)V" 1)   ; 7
       (methodref "java/lang/Math" "copySign:(DD)D" 4)         ; 8
       (double #xbff0000000000000) ; -0x1.0p0 -1.0             ; 9
       nil
       (string (ref -1) ; "-"
          45)                                                  ; 11
       (methodref "java/lang/StringBuilder" "append:(Ljava/lang/String;)Ljava/lang/StringBuilder;" 1)  ; 12
       (string (ref -1) ; "0x"
          48 120)                                              ; 13
       (methodref "java/lang/Math" "abs:(D)D" 2)               ; 14
       (string (ref -1) ; "0.0p0"
          48 46 48 112 48)                                     ; 15
       (class (ref -1) "jdk/internal/math/DoubleConsts")       ; 16
       (double #x0010000000000000) ; 0x1.0p-1022 2.2250738585072014E-308       ; 17
       nil
       (methodref "java/lang/Double" "doubleToLongBits:(D)J" 2)        ; 19
       (long 4503599627370495)                                 ; 20
       nil
       (long 1152921504606846976)                              ; 22
       nil
       (string (ref -1) ; "0."
          48 46)                                               ; 24
       (string (ref -1) ; "1."
          49 46)                                               ; 25
       (methodref "java/lang/Long" "toHexString:(J)Ljava/lang/String;" 2)      ; 26
       (methodref "java/lang/String" "substring:(II)Ljava/lang/String;" 2)     ; 27
       (string (ref -1) ; "0000000000000"
          48 48 48 48 48 48 48 48 48 48 48 48 48)              ; 28
       (methodref "java/lang/String" "equals:(Ljava/lang/Object;)Z" 1) ; 29
       (string (ref -1) ; "0"
          48)                                                  ; 30
       (string (ref -1) ; "0{1,12}$"
          48 123 49 44 49 50 125 36)                           ; 31
       (string (ref -1) ; ""
         )                                                     ; 32
       (methodref "java/lang/String" "replaceFirst:(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;" 2)        ; 33
       (methodref "java/lang/StringBuilder" "append:(C)Ljava/lang/StringBuilder;" 1)   ; 34
       (methodref "java/lang/Math" "getExponent:(D)I" 2)       ; 35
       (methodref "java/lang/StringBuilder" "append:(I)Ljava/lang/StringBuilder;" 1)   ; 36
       (methodref "java/lang/StringBuilder" "toString:()Ljava/lang/String;" 0) ; 37
       (methodref "java/lang/Double" "parseDouble:(Ljava/lang/String;)D" 1)    ; 38
       (methodref "java/lang/Double" "<init>:(D)V" 2)          ; 39
       (methodref "jdk/internal/math/FloatingDecimal" "parseDouble:(Ljava/lang/String;)D" 1)   ; 40
       (double #x7ff0000000000000) ; Infinity Infinity         ; 41
       nil
       (double #xfff0000000000000) ; -Infinity -Infinity       ; 43
       nil
       (double #x7fefffffffffffff) ; 0x1.fffffffffffffp1023 1.7976931348623157E308     ; 45
       nil
       (methodref "java/lang/Number" "<init>:()V" 0)           ; 47
       (fieldref "java/lang/Double" "value:D" 2)               ; 48
       (methodref "java/lang/Double" "isNaN:(D)Z" 2)           ; 49
       (methodref "java/lang/Double" "isInfinite:(D)Z" 2)      ; 50
       (methodref "java/lang/Double" "hashCode:(D)I" 2)        ; 51
       (methodref "java/lang/Double" "doubleToRawLongBits:(D)J" 2)     ; 52
       (long 9221120237041090560)                              ; 53
       nil
       (methodref "java/lang/Double" "compare:(DD)I" 4)        ; 55
       (methodref "java/lang/Math" "max:(DD)D" 4)              ; 56
       (methodref "java/lang/Math" "min:(DD)D" 4)              ; 57
       (methodref "java/lang/Double" "compareTo:(Ljava/lang/Double;)I" 1)      ; 58
       (string (ref -1) ; "double"
          100 111 117 98 108 101)                              ; 59
       (methodref "java/lang/Class" "getPrimitiveClass:(Ljava/lang/String;)Ljava/lang/Class;" 1)       ; 60
       (fieldref "java/lang/Double" "TYPE:Ljava/lang/Class;" 1)        ; 61
       (class (ref -1) "java/lang/Number")                     ; 62
       (class (ref -1) "java/lang/Comparable")                 ; 63
       (utf8)                                                  ; 64
       (utf8)                                                  ; 65
       (utf8)                                                  ; 66
       (utf8)                                                  ; 67
       (utf8)                                                  ; 68
       (double #x7ff8000000000000) ; NaN NaN                   ; 69
       nil
       (utf8)                                                  ; 71
       (utf8)                                                  ; 72
       (utf8)                                                  ; 73
       (double #x0000000000000001) ; 0x0.0000000000001p-1022 4.9E-324  ; 74
       nil
       (utf8)                                                  ; 76
       (utf8)                                                  ; 77
       (integer 1023)                                          ; 78
       (utf8)                                                  ; 79
       (integer -1022)                                         ; 80
       (utf8)                                                  ; 81
       (integer 64)                                            ; 82
       (utf8)                                                  ; 83
       (integer 8)                                             ; 84
       (utf8)                                                  ; 85
       (utf8)                                                  ; 86
       (utf8)                                                  ; 87
       (utf8)                                                  ; 88
       (utf8)                                                  ; 89
       (utf8)                                                  ; 90
       (utf8)                                                  ; 91
       (long -9172774392245257468)                             ; 92
       nil
       (utf8)                                                  ; 94
       (utf8)                                                  ; 95
       (utf8)                                                  ; 96
       (utf8)                                                  ; 97
       (utf8)                                                  ; 98
       (utf8)                                                  ; 99
       (class (ref -1) "java/lang/String")                     ; 100
       (utf8)                                                  ; 101
       (utf8)                                                  ; 102
       (utf8)                                                  ; 103
       (class (ref -1) "java/lang/NumberFormatException")      ; 104
       (utf8)                                                  ; 105
       (utf8)                                                  ; 106
       (utf8)                                                  ; 107
       (utf8)                                                  ; 108
       (utf8)                                                  ; 109
       (utf8)                                                  ; 110
       (utf8)                                                  ; 111
       (utf8)                                                  ; 112
       (utf8)                                                  ; 113
       (utf8)                                                  ; 114
       (utf8)                                                  ; 115
       (utf8)                                                  ; 116
       (utf8)                                                  ; 117
       (utf8)                                                  ; 118
       (utf8)                                                  ; 119
       (utf8)                                                  ; 120
       (utf8)                                                  ; 121
       (utf8)                                                  ; 122
       (utf8)                                                  ; 123
       (utf8)                                                  ; 124
       (utf8)                                                  ; 125
       (utf8)                                                  ; 126
       (utf8)                                                  ; 127
       (utf8)                                                  ; 128
       (utf8)                                                  ; 129
       (utf8)                                                  ; 130
       (utf8)                                                  ; 131
       (utf8)                                                  ; 132
       (utf8)                                                  ; 133
       (utf8)                                                  ; 134
       (utf8)                                                  ; 135
       (utf8)                                                  ; 136
       (utf8)                                                  ; 137
       (utf8)                                                  ; 138
       (utf8)                                                  ; 139
       (utf8)                                                  ; 140
       (utf8)                                                  ; 141
       (utf8)                                                  ; 142
       (utf8)                                                  ; 143
       (utf8)                                                  ; 144
       (utf8)                                                  ; 145
       (utf8)                                                  ; 146
       (utf8)                                                  ; 147
       (utf8)                                                  ; 148
       (utf8)                                                  ; 149
       (utf8)                                                  ; 150
       (utf8)                                                  ; 151
       (utf8)                                                  ; 152
       (utf8)                                                  ; 153
       (utf8)                                                  ; 154
       (utf8)                                                  ; 155
       (class (ref -1) "jdk/internal/math/FloatingDecimal")    ; 156
       (name-and-type "toJavaFormatString:(D)Ljava/lang/String;")      ; 157
       (name-and-type "isFinite:(D)Z")                         ; 158
       (name-and-type "toString:(D)Ljava/lang/String;")        ; 159
       (utf8)                                                  ; 160
       (name-and-type "<init>:(I)V")                           ; 161
       (class (ref -1) "java/lang/Math")                       ; 162
       (name-and-type "copySign:(DD)D")                        ; 163
       (utf8)                                                  ; 164
       (name-and-type "append:(Ljava/lang/String;)Ljava/lang/StringBuilder;")  ; 165
       (utf8)                                                  ; 166
       (name-and-type "abs:(D)D")                              ; 167
       (utf8)                                                  ; 168
       (utf8)                                                  ; 169
       (name-and-type "doubleToLongBits:(D)J")                 ; 170
       (utf8)                                                  ; 171
       (utf8)                                                  ; 172
       (class (ref -1) "java/lang/Long")                       ; 173
       (name-and-type "toHexString:(J)Ljava/lang/String;")     ; 174
       (name-and-type "substring:(II)Ljava/lang/String;")      ; 175
       (utf8)                                                  ; 176
       (name-and-type "equals:(Ljava/lang/Object;)Z")          ; 177
       (utf8)                                                  ; 178
       (utf8)                                                  ; 179
       (utf8)                                                  ; 180
       (name-and-type "replaceFirst:(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;") ; 181
       (name-and-type "append:(C)Ljava/lang/StringBuilder;")   ; 182
       (name-and-type "getExponent:(D)I")                      ; 183
       (name-and-type "append:(I)Ljava/lang/StringBuilder;")   ; 184
       (name-and-type "toString:()Ljava/lang/String;")         ; 185
       (name-and-type "parseDouble:(Ljava/lang/String;)D")     ; 186
       (name-and-type "<init>:(D)V")                           ; 187
       (name-and-type "<init>:()V")                            ; 188
       (name-and-type "value:D")                               ; 189
       (name-and-type "isNaN:(D)Z")                            ; 190
       (name-and-type "isInfinite:(D)Z")                       ; 191
       (name-and-type "hashCode:(D)I")                         ; 192
       (name-and-type "doubleToRawLongBits:(D)J")              ; 193
       (name-and-type "compare:(DD)I")                         ; 194
       (name-and-type "max:(DD)D")                             ; 195
       (name-and-type "min:(DD)D")                             ; 196
       (name-and-type "compareTo:(Ljava/lang/Double;)I")       ; 197
       (utf8)                                                  ; 198
       (class (ref -1) "java/lang/Class")                      ; 199
       (name-and-type "getPrimitiveClass:(Ljava/lang/String;)Ljava/lang/Class;")       ; 200
       (name-and-type "TYPE:Ljava/lang/Class;")                ; 201
       (utf8)                                                  ; 202
       (utf8)                                                  ; 203
       (utf8)                                                  ; 204
       (utf8)                                                  ; 205
       (utf8)                                                  ; 206
       (utf8)                                                  ; 207
       (utf8)                                                  ; 208
       (utf8)                                                  ; 209
       (utf8)                                                  ; 210
       (utf8)                                                  ; 211
       (utf8)                                                  ; 212
       (utf8)                                                  ; 213
       (utf8)                                                  ; 214
       (utf8)                                                  ; 215
       (utf8)                                                  ; 216
       (utf8)                                                  ; 217
       (utf8)                                                  ; 218
       (utf8)                                                  ; 219
       (utf8)                                                  ; 220
       (utf8)                                                  ; 221
       (utf8)                                                  ; 222
       (utf8)                                                  ; 223
       (utf8)                                                  ; 224
       (utf8)                                                  ; 225
       (utf8)                                                  ; 226
      )
     (list
      '("toString:(D)Ljava/lang/String;" nil
        ; line_number #204
        (dload_0)                                               ; 0
        (invokestatic 3)                                        ; 1 jdk.internal.math.FloatingDecimal.toJavaFormatString:(D)Ljava/lang/String;
        (areturn)                                               ; 4
       )
      '("toHexString:(D)Ljava/lang/String;" nil
        ; line_number #287
        (dload_0)                                               ; 0
        (invokestatic 4)                                        ; 1 java.lang.Double.isFinite:(D)Z
        (ifne 8)                                                ; 4
        ; line_number #289
        (dload_0)                                               ; 7
        (invokestatic 5)                                        ; 8 java.lang.Double.toString:(D)Ljava/lang/String;
        (areturn)                                               ; 11
        ; line_number #292
        (new 6)                                                 ; 12 class java.lang.StringBuilder
        (dup)                                                   ; 15
        (bipush 24)                                             ; 16
        (invokespecial 7)                                       ; 18 java.lang.StringBuilder.<init>:(I)V
        (astore_2)                                              ; 21
        ; line_number #294
        (dconst_1)                                              ; 22
        (dload_0)                                               ; 23
        (invokestatic 8)                                        ; 24 java.lang.Math.copySign:(DD)D
        (ldc2_w 9)                                              ; 27 -1.0d
        (dcmpl)                                                 ; 30
        (ifne 10)                                               ; 31
        ; line_number #295
        (aload_2)                                               ; 34
        (ldc 11)                                                ; 35 "-"
        (invokevirtual 12)                                      ; 37 java.lang.StringBuilder.append:(Ljava/lang/String;)Ljava/lang/StringBuilder;
        (pop)                                                   ; 40
        ; line_number #297
        (aload_2)                                               ; 41
        (ldc 13)                                                ; 42 "0x"
        (invokevirtual 12)                                      ; 44 java.lang.StringBuilder.append:(Ljava/lang/String;)Ljava/lang/StringBuilder;
        (pop)                                                   ; 47
        ; line_number #299
        (dload_0)                                               ; 48
        (invokestatic 14)                                       ; 49 java.lang.Math.abs:(D)D
        (dstore_0)                                              ; 52
        ; line_number #301
        (dload_0)                                               ; 53
        (dconst_0)                                              ; 54
        (dcmpl)                                                 ; 55
        (ifne 13)                                               ; 56
        ; line_number #302
        (aload_2)                                               ; 59
        (ldc 15)                                                ; 60 "0.0p0"
        (invokevirtual 12)                                      ; 62 java.lang.StringBuilder.append:(Ljava/lang/String;)Ljava/lang/StringBuilder;
        (pop)                                                   ; 65
        (goto 115)                                              ; 66
        ; line_number #304
        (dload_0)                                               ; 69
        (ldc2_w 17)                                             ; 70 2.2250738585072014E-308d
        (dcmpg)                                                 ; 73
        (ifge 7)                                                ; 74
        (iconst_1)                                              ; 77
        (goto 4)                                                ; 78
        (iconst_0)                                              ; 81
        (istore_3)                                              ; 82
        ; line_number #309
        (dload_0)                                               ; 83
        (invokestatic 19)                                       ; 84 java.lang.Double.doubleToLongBits:(D)J
        (ldc2_w 20)                                             ; 87 4503599627370495l
        (land)                                                  ; 90
        (ldc2_w 22)                                             ; 91 1152921504606846976l
        (lor)                                                   ; 94
        (lstore 4)                                              ; 95
        ; line_number #315
        (aload_2)                                               ; 97
        (iload_3)                                               ; 98
        (ifeq 8)                                                ; 99
        (ldc 24)                                                ; 102 "0."
        (goto 5)                                                ; 104
        (ldc 25)                                                ; 107 "1."
        (invokevirtual 12)                                      ; 109 java.lang.StringBuilder.append:(Ljava/lang/String;)Ljava/lang/StringBuilder;
        (pop)                                                   ; 112
        ; line_number #321
        (lload 4)                                               ; 113
        (invokestatic 26)                                       ; 115 java.lang.Long.toHexString:(J)Ljava/lang/String;
        (iconst_3)                                              ; 118
        (bipush 16)                                             ; 119
        (invokevirtual 27)                                      ; 121 java.lang.String.substring:(II)Ljava/lang/String;
        (astore 6)                                              ; 124
        ; line_number #322
        (aload_2)                                               ; 126
        (aload 6)                                               ; 127
        (ldc 28)                                                ; 129 "0000000000000"
        (invokevirtual 29)                                      ; 131 java.lang.String.equals:(Ljava/lang/Object;)Z
        (ifeq 8)                                                ; 134
        ; line_number #323
        (ldc 30)                                                ; 137 "0"
        (goto 12)                                               ; 139
        ; line_number #324
        (aload 6)                                               ; 142
        (ldc 31)                                                ; 144 "0{1,12}$"
        (ldc 32)                                                ; 146 ""
        (invokevirtual 33)                                      ; 148 java.lang.String.replaceFirst:(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
        ; line_number #322
        (invokevirtual 12)                                      ; 151 java.lang.StringBuilder.append:(Ljava/lang/String;)Ljava/lang/StringBuilder;
        (pop)                                                   ; 154
        ; line_number #326
        (aload_2)                                               ; 155
        (bipush 112)                                            ; 156
        (invokevirtual 34)                                      ; 158 java.lang.StringBuilder.append:(C)Ljava/lang/StringBuilder;
        (pop)                                                   ; 161
        ; line_number #331
        (aload_2)                                               ; 162
        (iload_3)                                               ; 163
        (ifeq 9)                                                ; 164
        ; line_number #332
        (sipush -1022)                                          ; 167
        (goto 7)                                                ; 170
        ; line_number #333
        (dload_0)                                               ; 173
        (invokestatic 35)                                       ; 174 java.lang.Math.getExponent:(D)I
        ; line_number #331
        (invokevirtual 36)                                      ; 177 java.lang.StringBuilder.append:(I)Ljava/lang/StringBuilder;
        (pop)                                                   ; 180
        ; line_number #335
        (aload_2)                                               ; 181
        (invokevirtual 37)                                      ; 182 java.lang.StringBuilder.toString:()Ljava/lang/String;
        (areturn)                                               ; 185
       )
      '("valueOf:(Ljava/lang/String;)Ljava/lang/Double;" nil
        ; line_number #502
        (new 1)                                                 ; 0 class java.lang.Double
        (dup)                                                   ; 3
        (aload_0)                                               ; 4
        (invokestatic 38)                                       ; 5 java.lang.Double.parseDouble:(Ljava/lang/String;)D
        (invokespecial 39)                                      ; 8 java.lang.Double.<init>:(D)V
        (areturn)                                               ; 11
       )
      '("valueOf:(D)Ljava/lang/Double;" nil
        ; line_number #520
        (new 1)                                                 ; 0 class java.lang.Double
        (dup)                                                   ; 3
        (dload_0)                                               ; 4
        (invokespecial 39)                                      ; 5 java.lang.Double.<init>:(D)V
        (areturn)                                               ; 8
       )
      '("parseDouble:(Ljava/lang/String;)D" nil
        ; line_number #539
        (aload_0)                                               ; 0
        (invokestatic 40)                                       ; 1 jdk.internal.math.FloatingDecimal.parseDouble:(Ljava/lang/String;)D
        (dreturn)                                               ; 4
       )
      '("isNaN:(D)Z" nil
        ; line_number #551
        (dload_0)                                               ; 0
        (dload_0)                                               ; 1
        (dcmpl)                                                 ; 2
        (ifeq 7)                                                ; 3
        (iconst_1)                                              ; 6
        (goto 4)                                                ; 7
        (iconst_0)                                              ; 10
        (ireturn)                                               ; 11
       )
      '("isInfinite:(D)Z" nil
        ; line_number #563
        (dload_0)                                               ; 0
        (ldc2_w 41)                                             ; 1 Infinityd
        (dcmpl)                                                 ; 4
        (ifeq 11)                                               ; 5
        (dload_0)                                               ; 8
        (ldc2_w 43)                                             ; 9 -Infinityd
        (dcmpl)                                                 ; 12
        (ifne 7)                                                ; 13
        (iconst_1)                                              ; 16
        (goto 4)                                                ; 17
        (iconst_0)                                              ; 20
        (ireturn)                                               ; 21
       )
      '("isFinite:(D)Z" nil
        ; line_number #577
        (dload_0)                                               ; 0
        (invokestatic 14)                                       ; 1 java.lang.Math.abs:(D)D
        (ldc2_w 45)                                             ; 4 1.7976931348623157E308d
        (dcmpg)                                                 ; 7
        (ifgt 7)                                                ; 8
        (iconst_1)                                              ; 11
        (goto 4)                                                ; 12
        (iconst_0)                                              ; 15
        (ireturn)                                               ; 16
       )
      '("<init>:(D)V" nil
        ; line_number #593
        (aload_0)                                               ; 0
        (invokespecial 47)                                      ; 1 java.lang.Number.<init>:()V
        ; line_number #594
        (aload_0)                                               ; 4
        (dload_1)                                               ; 5
        (putfield 48)                                           ; 6 java.lang.Double.value:D
        ; line_number #595
        (return)                                                ; 9
       )
      '("<init>:(Ljava/lang/String;)V" nil
        ; line_number #608
        (aload_0)                                               ; 0
        (invokespecial 47)                                      ; 1 java.lang.Number.<init>:()V
        ; line_number #609
        (aload_0)                                               ; 4
        (aload_1)                                               ; 5
        (invokestatic 38)                                       ; 6 java.lang.Double.parseDouble:(Ljava/lang/String;)D
        (putfield 48)                                           ; 9 java.lang.Double.value:D
        ; line_number #610
        (return)                                                ; 12
       )
      '("isNaN:()Z" nil
        ; line_number #620
        (aload_0)                                               ; 0
        (getfield 48)                                           ; 1 java.lang.Double.value:D
        (invokestatic 49)                                       ; 4 java.lang.Double.isNaN:(D)Z
        (ireturn)                                               ; 7
       )
      '("isInfinite:()Z" nil
        ; line_number #632
        (aload_0)                                               ; 0
        (getfield 48)                                           ; 1 java.lang.Double.value:D
        (invokestatic 50)                                       ; 4 java.lang.Double.isInfinite:(D)Z
        (ireturn)                                               ; 7
       )
      '("toString:()Ljava/lang/String;" nil
        ; line_number #645
        (aload_0)                                               ; 0
        (getfield 48)                                           ; 1 java.lang.Double.value:D
        (invokestatic 5)                                        ; 4 java.lang.Double.toString:(D)Ljava/lang/String;
        (areturn)                                               ; 7
       )
      '("byteValue:()B" nil
        ; line_number #658
        (aload_0)                                               ; 0
        (getfield 48)                                           ; 1 java.lang.Double.value:D
        (d2i)                                                   ; 4
        (i2b)                                                   ; 5
        (ireturn)                                               ; 6
       )
      '("shortValue:()S" nil
        ; line_number #671
        (aload_0)                                               ; 0
        (getfield 48)                                           ; 1 java.lang.Double.value:D
        (d2i)                                                   ; 4
        (i2s)                                                   ; 5
        (ireturn)                                               ; 6
       )
      '("intValue:()I" nil
        ; line_number #683
        (aload_0)                                               ; 0
        (getfield 48)                                           ; 1 java.lang.Double.value:D
        (d2i)                                                   ; 4
        (ireturn)                                               ; 5
       )
      '("longValue:()J" nil
        ; line_number #695
        (aload_0)                                               ; 0
        (getfield 48)                                           ; 1 java.lang.Double.value:D
        (d2l)                                                   ; 4
        (lreturn)                                               ; 5
       )
      '("floatValue:()F" nil
        ; line_number #708
        (aload_0)                                               ; 0
        (getfield 48)                                           ; 1 java.lang.Double.value:D
        (d2f)                                                   ; 4
        (freturn)                                               ; 5
       )
      '("doubleValue:()D" nil
        ; line_number #718
        (aload_0)                                               ; 0
        (getfield 48)                                           ; 1 java.lang.Double.value:D
        (dreturn)                                               ; 4
       )
      '("hashCode:()I" nil
        ; line_number #744
        (aload_0)                                               ; 0
        (getfield 48)                                           ; 1 java.lang.Double.value:D
        (invokestatic 51)                                       ; 4 java.lang.Double.hashCode:(D)I
        (ireturn)                                               ; 7
       )
      '("hashCode:(D)I" nil
        ; line_number #756
        (dload_0)                                               ; 0
        (invokestatic 19)                                       ; 1 java.lang.Double.doubleToLongBits:(D)J
        (lstore_2)                                              ; 4
        ; line_number #757
        (lload_2)                                               ; 5
        (lload_2)                                               ; 6
        (bipush 32)                                             ; 7
        (lushr)                                                 ; 9
        (lxor)                                                  ; 10
        (l2i)                                                   ; 11
        (ireturn)                                               ; 12
       )
      '("equals:(Ljava/lang/Object;)Z" nil
        ; line_number #800
        (aload_1)                                               ; 0
        (instanceof 1)                                          ; 1 class java.lang.Double
        (ifeq 28)                                               ; 4
        (aload_1)                                               ; 7
        (checkcast 1)                                           ; 8 class java.lang.Double
        (getfield 48)                                           ; 11 java.lang.Double.value:D
        ; line_number #801
        (invokestatic 19)                                       ; 14 java.lang.Double.doubleToLongBits:(D)J
        (aload_0)                                               ; 17
        (getfield 48)                                           ; 18 java.lang.Double.value:D
        ; line_number #802
        (invokestatic 19)                                       ; 21 java.lang.Double.doubleToLongBits:(D)J
        (lcmp)                                                  ; 24
        (ifne 7)                                                ; 25
        (iconst_1)                                              ; 28
        (goto 4)                                                ; 29
        (iconst_0)                                              ; 32
        ; line_number #800
        (ireturn)                                               ; 33
       )
      '("doubleToLongBits:(D)J" nil
        ; line_number #839
        (dload_0)                                               ; 0
        (invokestatic 49)                                       ; 1 java.lang.Double.isNaN:(D)Z
        (ifne 8)                                                ; 4
        ; line_number #840
        (dload_0)                                               ; 7
        (invokestatic 52)                                       ; 8 java.lang.Double.doubleToRawLongBits:(D)J
        (lreturn)                                               ; 11
        ; line_number #842
        (ldc2_w 53)                                             ; 12 9221120237041090560l
        (lreturn)                                               ; 15
       )
      '("doubleToRawLongBits:(D)J" nil
        ; native method
       )
      '("longBitsToDouble:(J)D" nil
        ; native method
       )
      '("compareTo:(Ljava/lang/Double;)I" nil
        ; line_number #979
        (aload_0)                                               ; 0
        (getfield 48)                                           ; 1 java.lang.Double.value:D
        (aload_1)                                               ; 4
        (getfield 48)                                           ; 5 java.lang.Double.value:D
        (invokestatic 55)                                       ; 8 java.lang.Double.compare:(DD)I
        (ireturn)                                               ; 11
       )
      '("compare:(DD)I" nil
        ; line_number #1001
        (dload_0)                                               ; 0
        (dload_2)                                               ; 1
        (dcmpg)                                                 ; 2
        (ifge 5)                                                ; 3
        ; line_number #1002
        (iconst_m1)                                             ; 6
        (ireturn)                                               ; 7
        ; line_number #1003
        (dload_0)                                               ; 8
        (dload_2)                                               ; 9
        (dcmpl)                                                 ; 10
        (ifle 5)                                                ; 11
        ; line_number #1004
        (iconst_1)                                              ; 14
        (ireturn)                                               ; 15
        ; line_number #1007
        (dload_0)                                               ; 16
        (invokestatic 19)                                       ; 17 java.lang.Double.doubleToLongBits:(D)J
        (lstore 4)                                              ; 20
        ; line_number #1008
        (dload_2)                                               ; 22
        (invokestatic 19)                                       ; 23 java.lang.Double.doubleToLongBits:(D)J
        (lstore 6)                                              ; 26
        ; line_number #1010
        (lload 4)                                               ; 28
        (lload 6)                                               ; 30
        (lcmp)                                                  ; 32
        (ifne 7)                                                ; 33
        (iconst_0)                                              ; 36
        (goto 16)                                               ; 37
        ; line_number #1011
        (lload 4)                                               ; 40
        (lload 6)                                               ; 42
        (lcmp)                                                  ; 44
        (ifge 7)                                                ; 45
        (iconst_m1)                                             ; 48
        (goto 4)                                                ; 49
        ; line_number #1012
        (iconst_1)                                              ; 52
        ; line_number #1010
        (ireturn)                                               ; 53
       )
      '("sum:(DD)D" nil
        ; line_number #1026
        (dload_0)                                               ; 0
        (dload_2)                                               ; 1
        (dadd)                                                  ; 2
        (dreturn)                                               ; 3
       )
      '("max:(DD)D" nil
        ; line_number #1040
        (dload_0)                                               ; 0
        (dload_2)                                               ; 1
        (invokestatic 56)                                       ; 2 java.lang.Math.max:(DD)D
        (dreturn)                                               ; 5
       )
      '("min:(DD)D" nil
        ; line_number #1054
        (dload_0)                                               ; 0
        (dload_2)                                               ; 1
        (invokestatic 57)                                       ; 2 java.lang.Math.min:(DD)D
        (dreturn)                                               ; 5
       )
      '("compareTo:(Ljava/lang/Object;)I" nil
        ; line_number #49
        (aload_0)                                               ; 0
        (aload_1)                                               ; 1
        (checkcast 1)                                           ; 2 class java.lang.Double
        (invokevirtual 58)                                      ; 5 java.lang.Double.compareTo:(Ljava/lang/Double;)I
        (ireturn)                                               ; 8
       )
      '("<clinit>:()V" nil
        ; line_number #139
        (ldc 59)                                                ; 0 "double"
        (invokestatic 60)                                       ; 2 java.lang.Class.getPrimitiveClass:(Ljava/lang/String;)Ljava/lang/Class;
        (putstatic 61)                                          ; 5 java.lang.Double.TYPE:Ljava/lang/Class;
        (return)                                                ; 8
       ))
     '(ref -1)))